#pragma once
#include <stdint.h>

// Numbers generated by upstream tools/gen_dex.py. The names are NOT here:
// they are trademarks, and keeping them out is what lets this tree be shared.
// The table itself lives in tamapoke_dex.cpp and its name fields are filled in
// at startup from /mons/names.bin, which the user generates from their own
// checkout of upstream (tools/tamapoke/make_dex_names.py).

#define DEX_COUNT 151
#define DEX_EEVEE 133  // rama al azar: 134/135/136

// rareza: 0 = solo por evolucion, 1 = comun, 2 = raro, 3 = legendario
enum : uint8_t { R_EVO = 0, R_COMUN, R_RARO, R_LEGENDARIO };

struct DexEntry {
  const char *name;
  uint8_t evolvesTo;    // numero de dex, 0 = forma final
  uint8_t evolveLevel;
  uint8_t rarity;       // sale de huevo si > 0
  uint16_t accent;      // color RGB565 del tipo para la UI
  uint8_t bHp, bAtk, bDef, bSpe;  // base stats reales de gen 1
  uint8_t biome;        // 0 pradera 1 playa 2 bosque 3 volcan 4 montana 5 nieve
};

extern DexEntry DEX_TBL[DEX_COUNT + 1];

// Fills in DEX_TBL[].name from the card. Returns false when names.bin is
// absent, in which case every entry reads as "#NNN" and the game still plays.
bool tamapoke_dex_load_names(void);

// The first egg of a run: the classic starters (plus Eevee).
static const int16_t CLASSIC_DEX[] = { 1, 4, 7, 25, 133 };
#define NUM_CLASSIC_DEX 5
