#!/usr/bin/env bash
# Final check before pushing the TamaPoke branch and uploading the core.
#
# Everything here has failed at least once during this port, which is why each
# one is a check and not a note. Run it, read the summary, then push.
#
#   ./tools/tamapoke/preflight.sh [base_branch]     (default: testbed)
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
BASE="${1:-testbed}"
cd "$REPO"

pass=0; fail=0
ok()   { printf '  \033[32mok\033[0m   %s\n' "$1"; pass=$((pass+1)); }
bad()  { printf '  \033[31mFAIL\033[0m %s\n' "$1"; fail=$((fail+1)); }
note() { printf '       %s\n' "$1"; }

echo "== 1. nothing shareable-breaking in the tree =="

# The names were taken out of dex.h and species.h precisely so the source could
# be handed out. A literal creeping back in undoes that silently.
n=$(git grep -lE '"(BULBASAUR|CHARMANDER|SQUIRTLE|PIKACHU|MEWTWO)"' -- Core/ tools/ 2>/dev/null | wc -l)
[ "$n" -eq 0 ] && ok "no trademarked display strings" || bad "trademarked strings in $n file(s)"

# Sprite packs, the assets container, thumbnails: CC BY-NC, never committed.
n=$(git ls-files | grep -cE '\.(bin|dat|pak|img|ppm|tpk2)$' || true)
[ "$n" -eq 0 ] && ok "no asset binaries tracked" || bad "$n asset binary/binaries tracked"

# The PokeAPI cache holds the localised names verbatim. It was committed once.
n=$(git ls-files | grep -c 'pokeapi_cache' || true)
[ "$n" -eq 0 ] && ok "no PokeAPI cache tracked" || bad "PokeAPI cache tracked ($n files)"

echo
echo "== 2. a default build is untouched =="

# TAMAPOKE defaults off and is absent from CI, so a release build must not see
# a single reference. This is the whole safety story.
if ! make help CHECK_DIRTY_SUBMODULE=0 >/dev/null 2>&1; then
    bad "make does not parse"
else
    ok "make parses"
    n=$(make CHECK_DIRTY_SUBMODULE=0 -n --no-print-directory 2>/dev/null | grep -c tamapoke || true)
    [ "$n" -eq 0 ] && ok "TAMAPOKE=0 pulls in nothing" || bad "TAMAPOKE=0 still references tamapoke ($n)"
fi

if grep -rq 'TAMAPOKE' .github/workflows/ 2>/dev/null; then
    bad "TAMAPOKE appears in a CI workflow -- it would ship in a release"
else
    ok "TAMAPOKE absent from CI workflows"
fi

echo
echo "== 3. the branch carries only this port =="

# The first attempt at this branch dragged four unrelated commits (an
# external/sm bump among them) toward a release. Only wiring may differ.
ALLOWED='Core/Inc/gw_linker.h|Core/Src/retro-go/rg_emulators.c|Makefile|Makefile.common|STM32H7B0VBTx_SDCARD.ld|.gitignore|docs/TAMAPOKE'
stray=$(git diff --name-only "$BASE" 2>/dev/null | grep -v tamapoke | grep -vE "^($ALLOWED)" || true)
if [ -z "$stray" ]; then
    ok "diff vs $BASE is TamaPoke + wiring only"
else
    bad "unrelated files differ from $BASE:"
    echo "$stray" | sed 's/^/         /'
fi

echo
echo "== 4. layout and rendering =="
if ./tools/tamapoke_harness/run.sh >/tmp/tp_preflight_harness.log 2>&1; then
    ok "$(grep -oE '[0-9]+/[0-9]+ screens clean' /tmp/tp_preflight_harness.log) (both languages)"
else
    bad "harness failed -- see /tmp/tp_preflight_harness.log"
    grep -E '^FAIL|ERROR: AddressSanitizer' /tmp/tp_preflight_harness.log | head -5 | sed 's/^/         /'
fi

echo
echo "== 5. it links, and it fits =="
ELF=build/gw_retro_go.elf
MAP=build/gw_retro_go.map
if [ ! -s "$MAP" ]; then
    note "no map yet -- build with TAMAPOKE=1 first, skipping budget check"
else
    s=$(grep -aoE '0x[0-9a-f]+ +__ram_emu_tamapoke_start__' "$MAP" | grep -oE '0x[0-9a-f]+' | head -1)
    e=$(grep -aoE '0x[0-9a-f]+ +__ram_emu_tamapoke_end__' "$MAP" | grep -oE '0x[0-9a-f]+' | head -1)
    if [ -n "$s" ] && [ -n "$e" ]; then
        used=$(( e - s ))
        # __RAM_EMU_LENGTH__ = 1024K - 300K
        budget=741376
        pct=$(( used * 100 / budget ))
        if [ "$used" -lt "$budget" ]; then
            ok "RAM_EMU ${used}/${budget} B (${pct}%)"
        else
            bad "RAM_EMU overflow: ${used}/${budget} B"
        fi
    else
        note "overlay symbols absent from the map -- was TAMAPOKE=1 set?"
    fi
fi

# A core that references a global only another core defines gets silently bound
# to that core's address. The build runs this too; running it here means a
# failure is seen before the push rather than after.
if [ -s "$ELF" ] && [ -x scripts/check_core_symbol_aliases.py ]; then
    if python3 scripts/check_core_symbol_aliases.py "$ELF" >/tmp/tp_alias.log 2>&1; then
        ok "no cross-overlay symbol aliasing"
    else
        bad "cross-overlay aliasing -- see /tmp/tp_alias.log"
    fi
fi

echo
echo "== 6. the card payload =="
for f in sd_content/roms/homebrew/TamaPoke.bin; do
    [ -s "$f" ] && ok "$(basename "$f") $(stat -c %s "$f") B" || note "$f not built yet"
done
note "assets .dat is generated by stage_sd.sh from your own upstream checkout"

echo
printf '%d passed, %d failed\n' "$pass" "$fail"
[ "$fail" -eq 0 ] || exit 1
