#!/usr/bin/env python3
# Generate a 12px-tall bitmap font atlas (C header) for the host preview, so the
# preview renders the same glyphs the device i18n font would (approximately):
# Hangul from NanumGothic, Latin/symbols from DejaVuSans. Only the codepoints in
# the UI label corpus + sample data are emitted.
from PIL import Image, ImageFont, ImageDraw
import sys

H = 12  # cell height (matches i18n_get_text_height())

NANUM = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"
DEJAVU = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf"

# All text the preview can show: UI labels + sample metadata + symbols + ASCII.
CORPUS = (
    "재생 곡 탐색 음량 정보 가사 셔플 메뉴 목록 없음 스크롤 닫기 음악 "
    "즐겨찾기 켜짐 꺼짐 전체 한곡 끄기 밝기 반복 비어있음 뒤로 이동 "
    "별빛 속으로 우리의 노래 봄날 사랑 너에게 첫 눈 밤하늘 바다 "
    "페이지 앨범 플레이리스트 영원히 그대 빗속에서 가을 겨울 "
    "▲▼◀▶♥♪★·-/:()[]"
    + "".join(chr(c) for c in range(32, 127))
)

fonts = {}
def get_font(path, size):
    key = (path, size)
    if key not in fonts:
        fonts[key] = ImageFont.truetype(path, size)
    return fonts[key]

def is_hangul(cp):
    return 0xAC00 <= cp <= 0xD7A3 or 0x3130 <= cp <= 0x318F

def render(cp):
    ch = chr(cp)
    # pick font + size so glyphs sit in a 12px cell with a small descender room
    if is_hangul(cp):
        font = get_font(NANUM, 12); base = 11
    else:
        font = get_font(DEJAVU, 14); base = 11
    img = Image.new("L", (24, 16), 0)
    d = ImageDraw.Draw(img)
    d.text((1, base), ch, font=font, fill=255, anchor="ls")
    bbox = img.getbbox()
    if bbox is None:               # whitespace
        adv = 6 if ch == " " else 4
        return adv, [0] * H
    l, t, r, b = bbox
    w = min(16, r + 1)             # advance ~ ink right edge + 1px
    rows = []
    px = img.load()
    for y in range(H):
        bits = 0
        for x in range(w):
            if px[x, y] > 110:
                bits |= (1 << x)
        rows.append(bits)
    return w, rows

cps = sorted(set(ord(c) for c in CORPUS if ord(c) >= 32))
out = []
out.append("// Auto-generated by host/gen_font.py — 12px preview font atlas.")
out.append("#pragma once")
out.append("typedef struct { unsigned int cp; unsigned char w; unsigned short rows[12]; } glyph_t;")
out.append("static const glyph_t GLYPHS[] = {")
for cp in cps:
    w, rows = render(cp)
    out.append("  {%d,%d,{%s}}," % (cp, w, ",".join(str(r) for r in rows)))
out.append("};")
out.append("static const int GLYPH_N = %d;" % len(cps))

open("host/font_data.h", "w").write("\n".join(out) + "\n")
print("wrote host/font_data.h with %d glyphs" % len(cps))
