#!/usr/bin/env python3
# Bake Lucide icons (https://lucide.dev, ISC licence — a Feather fork) into
# 1-bit pix_icon_t sprites for the Clock app. Renders each 24px stroke SVG at
# the target size with anti-aliasing, then thresholds to 1-bit.
# Output: Core/Src/retro-go/rg_clock_icons.h (committed; re-run to refresh).
import io, urllib.request
import cairosvg
from PIL import Image

# name -> (lucide icon, target px)
ICONS = {
    "PIX_CLOCK":     ("clock",         13),
    "PIX_TOMATO":    ("target",        13),   # pomodoro = focus rings
    "PIX_HOURGLASS": ("hourglass",     13),
    "PIX_STOPWATCH": ("timer",         13),
    "PIX_BELL":      ("bell",          12),
    "PIX_MOON":      ("moon",          12),
    "PIX_MUG":       ("coffee",        12),
    "PIX_CHEV_L":    ("chevron-left",  11),
    "PIX_CHEV_R":    ("chevron-right", 11),
}
URL = "https://unpkg.com/lucide-static@0.452.0/icons/%s.svg"

def bake(svg, px):
    # thicken the stroke a touch so 1-bit survives the downscale
    svg = svg.replace('stroke-width="2"', 'stroke-width="2.6"')
    png = cairosvg.svg2png(bytestring=svg.encode(), output_width=px*8, output_height=px*8,
                           background_color="white")
    im = Image.open(io.BytesIO(png)).convert("L").resize((px, px), Image.LANCZOS)
    rows = []
    for y in range(px):
        v = 0
        for x in range(px):
            if im.getpixel((x, y)) < 160:          # dark = ink
                v |= 1 << (px - 1 - x)
        rows.append(v)
    # trim fully-empty top/bottom rows
    while rows and rows[0] == 0: rows.pop(0)
    while rows and rows[-1] == 0: rows.pop()
    return px, rows

out = ["/* Generated by host/gen_icons.py from Lucide icons (lucide.dev, ISC",
       " * licence, a fork of Feather/MIT). 1-bit sprites for rg_clock.c. */",
       "#pragma once", "#include <stdint.h>", "",
       "typedef struct { uint8_t w, h; const uint16_t *rows; } pix_icon_t;", ""]
for cname, (icon, px) in ICONS.items():
    svg = urllib.request.urlopen(URL % icon, timeout=15).read().decode()
    w, rows = bake(svg, px)
    out.append(f"static const uint16_t {cname}_ROWS[{len(rows)}] = {{ " +
               ", ".join(f"0x{v:04x}" for v in rows) + " };")
    out.append(f"static const pix_icon_t {cname} = {{ {w}, {len(rows)}, {cname}_ROWS }};")
    print(f"{cname:15s} <- lucide/{icon} ({w}x{len(rows)})")
open("Core/Src/retro-go/rg_clock_icons.h", "w").write("\n".join(out) + "\n")
print("wrote Core/Src/retro-go/rg_clock_icons.h")
