#!/usr/bin/env python3
# Extract the real G&W logo bitmap (logo_gnw) from rg_logos.c into a header
# for host/clock_preview.c, so the preview draws the EXACT device logo.
import re

src = open("Core/Src/retro-go/rg_logos.c", encoding="utf-8").read()
m = re.search(r"const retro_logo_image logo_gnw[^=]*=\s*\{(.*?)\n\};", src, re.S)
assert m, "logo_gnw not found"
body = m.group(1)
nums = re.findall(r"(?<![\w.])(?:0x[0-9a-fA-F]+|\d+)(?![\w.])",
                  re.sub(r"//[^\n]*", "", body))
w, h = int(nums[0], 0), int(nums[1], 0)
data = [int(n, 0) for n in nums[2:]]
need = ((w + 7)//8) * h
assert len(data) >= need, (len(data), need)
with open("host/logo_gnw.h", "w") as f:
    f.write("/* generated by host/gen_logo.py from rg_logos.c — do not edit */\n")
    f.write(f"static const int LOGO_W = {w}, LOGO_H = {h};\n")
    f.write("static const unsigned char LOGO_BITS[] = {\n")
    for i in range(0, need, 12):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i+12]) + ",\n")
    f.write("};\n")
print(f"host/logo_gnw.h: {w}x{h}, {need} bytes")
