// Host preview harness: renders the real media_ui.c screens to a framebuffer
// and dumps raw RGB565 so render.py can turn them into PNGs. Text uses a 12px
// bitmap atlas (Nanum/DejaVu) generated by gen_font.py; cover art is synthesised.
#include "media_ui.h"
#include "media_lyrics.h"
#include "gui.h"
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "font_data.h"

#define W 320
#define H 240

static uint16_t fb[W * H];
void *lcd_get_active_buffer(void) { return fb; }
void *lcd_clear_active_buffer(void) { memset(fb, 0, sizeof(fb)); return fb; }
void lcd_swap(void) {}
uint8_t lcd_backlight_get(void) { return 8; }
void lcd_backlight_set(uint8_t b) { (void)b; }
void lcd_backlight_on(void) {}
void lcd_backlight_off(void) {}

// theme (dark, premium): tweak here to match the device theme being designed for
static colors_t theme = { 0 };
colors_t *curr_colors = &theme;

static uint16_t rgb(int r, int g, int b)
{
    return (uint16_t)(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3));
}

// --- i18n stub (bitmap atlas) ----------------------------------------------
int i18n_get_text_height(void) { return 12; }

static int utf8_next(const char **p)
{
    const unsigned char *s = (const unsigned char *)*p;
    if (*s == 0) return -1;
    int cp, n;
    if (*s < 0x80) { cp = *s; n = 1; }
    else if ((*s & 0xE0) == 0xC0) { cp = *s & 0x1F; n = 2; }
    else if ((*s & 0xF0) == 0xE0) { cp = *s & 0x0F; n = 3; }
    else { cp = *s & 0x07; n = 4; }
    for (int i = 1; i < n; i++) cp = (cp << 6) | (s[i] & 0x3F);
    *p += n;
    return cp;
}

static const glyph_t *glyph(int cp)
{
    for (int i = 0; i < GLYPH_N; i++) if ((int)GLYPHS[i].cp == cp) return &GLYPHS[i];
    return NULL;
}

int i18n_get_text_width(const char *t)
{
    if (!t) return 0;
    int w = 0, first = 1;
    const char *p = t;
    int cp;
    while ((cp = utf8_next(&p)) > 0) {
        const glyph_t *g = glyph(cp);
        int gw = g ? g->w : 8;
        w += (first ? 0 : 1) + gw;
        first = 0;
    }
    return w;
}

int i18n_draw_text_line(uint16_t x, uint16_t y, uint16_t width, const char *t,
                        uint16_t fg, uint16_t bg, char transparent)
{
    if (!transparent)
        for (int j = 0; j < 12; j++)
            for (int i = 0; i < width; i++)
                if (x + i < W && y + j < H) fb[(y + j) * W + x + i] = bg;
    if (!t) return 12;
    int cx = x;
    const char *p = t;
    int cp;
    while ((cp = utf8_next(&p)) > 0) {
        const glyph_t *g = glyph(cp);
        int gw = g ? g->w : 8;
        if (cx + gw > x + width) break;
        if (g) {
            for (int row = 0; row < 12; row++) {
                unsigned bits = g->rows[row];
                for (int bx = 0; bx < 16; bx++)
                    if (bits & (1u << bx)) {
                        int px = cx + bx, py = y + row;
                        if (px >= 0 && px < W && py >= 0 && py < H) fb[py * W + px] = fg;
                    }
            }
        }
        cx += gw + 1;
    }
    return 12;
}

int i18n_draw_text(uint16_t x, uint16_t y, uint16_t w, uint16_t h, const char *t,
                   uint16_t fg, uint16_t bg, char transparent)
{ return i18n_draw_text_line(x, y, w, t, fg, bg, transparent); }

// --- cover stubs (synthetic art) -------------------------------------------
int audio_bitrate_kbps(void) { return 320; }
int audio_src_hz(void) { return 44100; }
int audio_channels(void) { return 2; }

static int g_have_cover = 1;

int cover_load(const char *path, bool *is_png) { (void)path; *is_png = false; return g_have_cover; }

bool cover_render_backdrop(int n, bool is_png)
{
    (void)is_png;
    if (n <= 0) return false;
    for (int y = 0; y < H; y++)
        for (int x = 0; x < W; x++) {        // vivid diagonal "photo", then dimmed
            int t = (x + y);
            int r = 30 + (t * 200) / (W + H);
            int gg = 20 + ((W + H - t) * 120) / (W + H);
            int b = 90 + (y * 140) / H;
            uint16_t c = rgb(r, gg, b);
            c = (uint16_t)((c >> 1) & 0x7BEF);
            c = (uint16_t)((c >> 1) & 0x7BEF);
            fb[y * W + x] = c;
        }
    return true;
}

bool cover_render_card(int n, bool is_png, int bx, int by, int bw, int bh)
{
    (void)is_png;
    if (n <= 0) return false;
    for (int y = 0; y < bh; y++)
        for (int x = 0; x < bw; x++) {        // bright album-art stand-in
            int r = 230 - (y * 160) / bh;
            int gg = 60 + (x * 150) / bw;
            int b = 120 + (y * 110) / bh;
            fb[(by + y) * W + (bx + x)] = rgb(r, gg < 255 ? gg : 255, b < 255 ? b : 255);
        }
    return true;
}

bool cover_thumb(const char *p, uint16_t *out, int sz)
{
    (void)p;
    for (int y = 0; y < sz; y++) {
        for (int x = 0; x < sz; x++) {
            out[y * sz + x] = (uint16_t)((((x * 31 / sz) & 0x1F) << 11) | 
                                         ((((12 + y * 40 / sz) & 0x3F) << 5)) | 
                                         ((x * y * 31 / (sz * sz)) & 0x1F));
        }
    }
    return true;
}

// --- scenes -----------------------------------------------------------------
static void dump(const char *name)
{
    char path[128];
    snprintf(path, sizeof(path), "/tmp/mpv/%s.bin", name);
    FILE *f = fopen(path, "wb");
    fwrite(fb, 2, W * H, f);
    fclose(f);
}

static void fill_tags(player_state_t *ps)
{
    memset(ps, 0, sizeof(*ps));
    strcpy(ps->tags.title, "\xEB\xB3\x84\xEB\xB9\x9B \xEC\x86\x8D\xEC\x9C\xBC\xEB\xA1\x9C");   // 별빛 속으로
    strcpy(ps->tags.artist, "\xEC\x9A\xB0\xEB\xA6\xAC\xEC\x9D\x98 \xEB\x85\xB8\xEB\x9E\x98"); // 우리의 노래
    strcpy(ps->tags.album, "\xEB\xB4\x84\xEB\x82\xA0");                                        // 봄날
    strcpy(ps->tags.year, "2024");
    strcpy(ps->tags.genre, "Indie Pop");
    strcpy(ps->tags.track, "3/12");
    strcpy(ps->tags.composer, "Kim");
    ps->title = ps->tags.title;
    ps->artist = ps->tags.artist;
    ps->album = ps->tags.album;
    ps->sec = 72; ps->total = 215;
    ps->track_index = 2; ps->track_count = 12;
    ps->paused = false; ps->shuffle = true; ps->favorite = true;
    ps->repeat = REPEAT_ALL; ps->volume = 6;
    ps->file_size = 5L * 1024 * 1024;
    ps->scrub = -1.0f;
}

// --- list scene ---
static uint16_t g_thumb[28 * 28];
static void mk_thumb(void)
{
    for (int j = 0; j < 28; j++)
        for (int i = 0; i < 28; i++)
            g_thumb[j * 28 + i] = rgb(60 + i * 6, 40 + j * 5, 150 - i * 3);
}
static const char *SONGS[] = {
    "\xEB\xB3\x84\xEB\xB9\x9B", "\xEC\x86\x8D\xEC\x9C\xBC\xEB\xA1\x9C",
    "\xEB\xB4\x84\xEB\x82\xA0", "\xEC\x82\xAC\xEB\x9E\x91",
    "\xEB\xB0\xA4\xED\x95\x98\xEB\x8A\x98", "\xEB\xB0\x94\xEB\x8B\xA4",
    "\xEA\xB7\xB8\xEB\x8C\x80", "\xEA\xB0\x80\xEC\x9D\x84",
};
static const char *ARTISTS[] = {
    "\xEC\x9A\xB0\xEB\xA6\xAC\xEC\x9D\x98 \xEB\x85\xB8\xEB\x9E\x98",  // 우리의 노래
    "Queen", "\xEA\xB7\xB8\xEB\x8C\x80",  "IU",
};
static void list_item(int i, list_item_t *out)
{
    memset(out, 0, sizeof(*out));
    if (i == 0) { out->kind = LIST_SPECIAL; out->title = "\xE2\x98\x85 \xEC\xA6\x90\xEA\xB2\xA8\xEC\xB0\xBE\xEA\xB8\xB0 (5)"; return; }
    if (i == 1) { out->kind = LIST_DIR; out->title = "\xEC\x95\xA8\xEB\xB2\x94"; return; }                 // 앨범
    if (i == 2) { out->kind = LIST_DIR; out->title = "\xED\x94\x8C\xEB\xA0\x88\xEC\x9D\xB4\xEB\xA6\xAC\xEC\x8A\xA4\xED\x8A\xB8"; return; } // 플레이리스트
    static char t[80], d[12];
    if (i == 4 || i == 40)
        snprintf(t, sizeof(t), "\xEB\xB3\x84\xEB\xB9\x9B \xEC\x86\x8D\xEC\x9C\xBC\xEB\xA1\x9C \xEC\x98\x81\xEC\x9B\x90\xED\x9E\x88 \xEA\xB7\xB8\xEB\x8C\x80 \xEB\xB9\x97\xEC\x86\x8D\xEC\x97\x90\xEC\x84\x9C"); // long title
    else
        snprintf(t, sizeof(t), "%s %s", SONGS[i % 8], SONGS[(i + 3) % 8]);
    snprintf(d, sizeof(d), "%d:%02d", 2 + (i % 4), (i * 7) % 60);
    out->kind = LIST_TRACK;
    out->title = t;
    out->subtitle = ARTISTS[i % 4];
    out->duration = d;
    out->art = (i % 3) ? g_thumb : NULL;
    out->art_sz = 28;
    out->fav = (i % 6 == 0);
}

int main(void)
{
    system("mkdir -p /tmp/mpv");
    theme.bg_c = rgb(16, 18, 28);
    theme.main_c = rgb(240, 242, 250);
    theme.sel_c = rgb(90, 200, 255);
    theme.dis_c = rgb(120, 126, 150);

    player_state_t ps; fill_tags(&ps);

    g_have_cover = 1;
    ui_player_static(&ps, 1, false);
    ui_player_dynamic(&ps);
    dump("nowplaying");

    g_have_cover = 0;
    ui_player_static(&ps, 0, false);
    ui_player_dynamic(&ps);
    dump("nowplaying_nocover");

    g_have_cover = 1;
    ui_info_draw(&ps);
    dump("info");

    char lrc[] = "[00:00.00]\xEB\xB3\x84\xEB\xB9\x9B\n[00:03.50]\xEC\x86\x8D\xEC\x9C\xBC\xEB\xA1\x9C\n[01:12.00]\xEC\x9A\xB0\xEB\xA6\xAC\xEC\x9D\x98 \xEB\x85\xB8\xEB\x9E\x98\n";
    lyrics_t ly; lyrics_parse(lrc, &ly);
    int act = lyrics_active_line(&ly, 72000);
    ui_lyrics_draw(&ps, &ly, act > 3 ? act - 3 : 0, act);
    dump("lyrics");

    // list: top of a large library (special + dirs + tracks, scrollbar)
    mk_thumb();
    list_view_t lv = { "/music", 342, 4, 0, LIST_VISIBLE_ROWS, LIST_ROW_H, false };
    ui_list_draw(&lv, list_item);
    dump("list_top");

    // list: mid-scroll (scrollbar mid, long title ellipsis on the selected row)
    lv.cursor = 40; lv.scroll = 37;
    ui_list_draw(&lv, list_item);
    dump("list_scroll");

    printf("rendered scenes to /tmp/mpv/*.bin\n");
    return 0;
}
