#!/usr/bin/env python3
"""
Generate DWT-instrumented copies of external/sm/src/snes/{apu.c,dsp.c} for
on-device SNES_LOAD_DIAG profiling. Mirrors tools/m7_qemu_rig/build_snes_cost.sh
but uses DWT_CYCCNT (the Cortex-M7 cycle counter) instead of rig_timer_now(),
and emits globals already prefixed with gsnes__ so the snes_redefines
--redefine-syms pass leaves them untouched.

external/ is NEVER edited -- only generated copies under $(BUILD_DIR)/snes_diag/.

The script writes three files into the output directory it is given:
  apu.c             -- apu.c with both spc_runOpcode and dsp_cycle call sites
                       bracketed by DWT deltas (each appears exactly twice in
                       the upstream source: once in legacy apu_cycle, once in
                       the batched apu_run hot path; both are wrapped so the
                       measurement follows the runtime path whichever is taken)
  dsp.c             -- dsp.c with the single dsp_handleEcho call site bracketed
                       (the FIR echo filter -- the suspected hot path that a
                       16 kHz mono decimation would shrink; the fast-path goto
                       inside the function stays put, we measure wall time)
  snes_diag_accum.h -- extern declarations for the three accumulators; the
                       Makefile forces -include of this header when
                       SNES_LOAD_DIAG=1 so main_snes.c and the generated dsp.c
                       see the externs without a manual #include

Accumulators (defined in the generated apu.c, declared in the header, read by
the SNES_LOAD_DIAG block in main_snes.c):
  gsnes__g_diag_spc_cycles        -- total cycles in spc_runOpcode (SPC700 CPU)
  gsnes__g_diag_dsp_cycles        -- total cycles in dsp_cycle (DSP total)
  gsnes__g_diag_dsp_echo_cycles   -- total cycles in dsp_handleEcho (echo FIR
                                     subset of DSP; non-echo DSP = dsp - echo)

Usage: instrument.py <apu.c-in> <dsp.c-in> <out-dir>
"""
import os
import sys


# Cortex-M7 DWT_CYCCNT register (0xE0001004), raw volatile read. Wrapped in a
# static inline so each instrumentation site stays self-contained: no extern,
# no header dependency, no risk of name clash with the SNES core's own symbols.
# Inlining also keeps the per-call overhead to a handful of cycles, which
# matters -- spc_runOpcode fires ~10,000x per frame.
DWT_READER = (
    "static inline uint32_t _diag_dwt_now(void) {\n"
    "    return *(volatile uint32_t*)0xE0001004;\n"
    "}\n"
)


APU_PRELUDE = (
    "/* Generated by tools/snes_diag/instrument.py -- DO NOT EDIT.\n"
    " * DWT-instrumented copy of external/sm/src/snes/apu.c for SNES_LOAD_DIAG.\n"
    " * The original apu.c follows unchanged below; only the two call sites\n"
    " * named below are bracketed. */\n"
    "#include <stdint.h>\n"
    "\n"
    + DWT_READER +
    "\n"
    "/* Profiling accumulators. The gsnes__ prefix is already the post-rename\n"
    " * name (snes_redefines maps the unprefixed token, not this one), so the\n"
    " * --redefine-syms pass leaves them alone. main_snes.c references these by\n"
    " * their full gsnes__ name; the generated dsp.c sees them via the forced\n"
    " * -include of snes_diag_accum.h. */\n"
    "uint64_t gsnes__g_diag_spc_cycles = 0;\n"
    "uint64_t gsnes__g_diag_dsp_cycles = 0;\n"
    "uint64_t gsnes__g_diag_dsp_echo_cycles = 0;\n"
    "\n"
)


DSP_PRELUDE = (
    "/* Generated by tools/snes_diag/instrument.py -- DO NOT EDIT.\n"
    " * DWT-instrumented copy of external/sm/src/snes/dsp.c for SNES_LOAD_DIAG.\n"
    " * The original dsp.c follows unchanged below; only the single\n"
    " * dsp_handleEcho call site is bracketed. */\n"
    "#include <stdint.h>\n"
    "\n"
    + DWT_READER +
    "\n"
)


HEADER = (
    "/* Generated by tools/snes_diag/instrument.py -- DO NOT EDIT.\n"
    " * Declares the SNES_LOAD_DIAG profiling accumulators (defined in the\n"
     " * generated apu.c). The Makefile forces -include of this header when\n"
    " * SNES_LOAD_DIAG=1 so main_snes.c and the generated dsp.c see the externs\n"
    " * without a manual #include. The gsnes__ prefix matches the post-rename\n"
    " * symbol name (snes_redefines does not touch these tokens because they\n"
    " * are already prefixed). */\n"
    "#ifndef SNES_DIAG_ACCUM_H\n"
    "#define SNES_DIAG_ACCUM_H\n"
    "#include <stdint.h>\n"
    "extern uint64_t gsnes__g_diag_spc_cycles;\n"
    "extern uint64_t gsnes__g_diag_dsp_cycles;\n"
    "extern uint64_t gsnes__g_diag_dsp_echo_cycles;\n"
    "#endif\n"
)


def instrument_apu(src):
    """Bracket spc_runOpcode and dsp_cycle call sites.

    Each call appears exactly twice in upstream apu.c (once in legacy
    apu_cycle, once in batched apu_run); we wrap both so whichever path the
    runtime takes is accounted. The assertion counts match
    tools/m7_qemu_rig/build_snes_cost.sh and fail loudly if upstream drifts.
    """
    n_spc = src.count("spc_runOpcode(apu->spc)")
    n_dsp = src.count("dsp_cycle(apu->dsp);")
    assert n_spc == 2, "expected 2 spc_runOpcode sites in apu.c, found %d" % n_spc
    assert n_dsp == 2, "expected 2 dsp_cycle sites in apu.c, found %d" % n_dsp

    # spc_runOpcode returns int (cycles consumed) -- preserve via gcc statement
    # expression so the assignment to cpuCyclesLeft stays intact. str.replace
    # is non-recursive: the spc_runOpcode token inside the replacement is not
    # re-matched, so the inserted call survives untouched.
    src = src.replace(
        "spc_runOpcode(apu->spc)",
        "({ uint32_t _dt = _diag_dwt_now(); "
        "int _r = spc_runOpcode(apu->spc); "
        "gsnes__g_diag_spc_cycles += (uint64_t)(_diag_dwt_now() - _dt); "
        "_r; })")

    # dsp_cycle returns void -- a plain brace block suffices.
    src = src.replace(
        "dsp_cycle(apu->dsp);",
        "{ uint32_t _dt = _diag_dwt_now(); "
        "dsp_cycle(apu->dsp); "
        "gsnes__g_diag_dsp_cycles += (uint64_t)(_diag_dwt_now() - _dt); }")

    return src


def instrument_dsp(src):
    """Bracket the single dsp_handleEcho call site in dsp.c.

    dsp_handleEcho is the FIR echo filter -- the work a 16 kHz mono decimation
    would actually remove (it is real arithmetic, not idle spin like the rc
    fast path, so cutting it shows up as real cycles). Only ONE call site at
    dsp.c:146. The fast-path goto inside the function stays; we measure wall
    time of the function including that fast path, which is exactly the cost
    the device pays per dsp_cycle tick.
    """
    n = src.count("dsp_handleEcho(dsp, &totalL, &totalR);")
    assert n == 1, "expected 1 dsp_handleEcho site in dsp.c, found %d" % n

    src = src.replace(
        "dsp_handleEcho(dsp, &totalL, &totalR);",
        "{ uint32_t _dt = _diag_dwt_now(); "
        "dsp_handleEcho(dsp, &totalL, &totalR); "
        "gsnes__g_diag_dsp_echo_cycles += (uint64_t)(_diag_dwt_now() - _dt); }")

    return src


def main():
    if len(sys.argv) != 4:
        sys.exit("usage: instrument.py <apu.c-in> <dsp.c-in> <out-dir>")
    apu_in, dsp_in, out_dir = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(apu_in, encoding="utf-8") as f:
        apu_src = f.read()
    with open(dsp_in, encoding="utf-8") as f:
        dsp_src = f.read()

    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, "apu.c"), "w", encoding="utf-8") as f:
        f.write(APU_PRELUDE + instrument_apu(apu_src))
    with open(os.path.join(out_dir, "dsp.c"), "w", encoding="utf-8") as f:
        f.write(DSP_PRELUDE + instrument_dsp(dsp_src))
    with open(os.path.join(out_dir, "snes_diag_accum.h"), "w", encoding="utf-8") as f:
        f.write(HEADER)

    print("SNES_LOAD_DIAG: wrote instrumented apu.c, dsp.c, snes_diag_accum.h -> %s"
          % out_dir)


if __name__ == "__main__":
    main()
