/* Generated by host/gen_icons.py from Lucide icons (lucide.dev, ISC
 * licence, a fork of Feather/MIT). 1-bit sprites for rg_clock.c. */
#pragma once
#include <stdint.h>

typedef struct { uint8_t w, h; const uint16_t *rows; } pix_icon_t;

static const uint16_t PIX_CLOCK_ROWS[13] = { 0x00e0, 0x03f8, 0x060c, 0x0c46, 0x0842, 0x1843, 0x1863, 0x1833, 0x0802, 0x0c06, 0x060c, 0x03f8, 0x00e0 };
static const pix_icon_t PIX_CLOCK = { 13, 13, PIX_CLOCK_ROWS };
static const uint16_t PIX_TOMATO_ROWS[13] = { 0x00e0, 0x03f8, 0x064c, 0x0df6, 0x0b1a, 0x1aeb, 0x1eef, 0x1aeb, 0x0b1a, 0x0df6, 0x064c, 0x03f8, 0x00e0 };
static const pix_icon_t PIX_TOMATO = { 13, 13, PIX_TOMATO_ROWS };
static const uint16_t PIX_HOURGLASS_ROWS[13] = { 0x07fc, 0x07fc, 0x0318, 0x0318, 0x03b8, 0x01f0, 0x00e0, 0x01f0, 0x03b8, 0x0318, 0x0318, 0x07fc, 0x07fc };
static const pix_icon_t PIX_HOURGLASS = { 13, 13, PIX_HOURGLASS_ROWS };
static const uint16_t PIX_STOPWATCH_ROWS[13] = { 0x00e0, 0x00e0, 0x0040, 0x03f8, 0x071c, 0x063c, 0x0c76, 0x0c66, 0x0c06, 0x060c, 0x071c, 0x03f8, 0x00e0 };
static const pix_icon_t PIX_STOPWATCH = { 13, 13, PIX_STOPWATCH_ROWS };
static const uint16_t PIX_BELL_ROWS[12] = { 0x0060, 0x01f8, 0x0108, 0x030c, 0x030c, 0x030c, 0x0204, 0x0606, 0x07fe, 0x0000, 0x00f0, 0x0060 };
static const pix_icon_t PIX_BELL = { 12, 12, PIX_BELL_ROWS };
static const uint16_t PIX_MOON_ROWS[10] = { 0x01e0, 0x03c0, 0x06c0, 0x06c0, 0x0462, 0x047e, 0x061e, 0x0606, 0x039c, 0x01f8 };
static const pix_icon_t PIX_MOON = { 12, 10, PIX_MOON_ROWS };
static const uint16_t PIX_MUG_ROWS[11] = { 0x0210, 0x03f0, 0x0000, 0x07fc, 0x07fe, 0x040b, 0x040b, 0x040e, 0x040c, 0x0618, 0x03f0 };
static const pix_icon_t PIX_MUG = { 12, 11, PIX_MUG_ROWS };
static const uint16_t PIX_CHEV_L_ROWS[7] = { 0x0010, 0x0030, 0x0060, 0x0040, 0x0060, 0x0030, 0x0010 };
static const pix_icon_t PIX_CHEV_L = { 11, 7, PIX_CHEV_L_ROWS };
static const uint16_t PIX_CHEV_R_ROWS[7] = { 0x0040, 0x0060, 0x0030, 0x0010, 0x0030, 0x0060, 0x0040 };
static const pix_icon_t PIX_CHEV_R = { 11, 7, PIX_CHEV_R_ROWS };
