#!/usr/bin/env python3
"""Render Korean console-name header images with the Yeon Sung font into
1-bit `retro_logo_image` C structs (same packing as png_to_logo.py:
row-major, width padded to a multiple of 8, MSB-first, visible pixel = 1).

These are the Korean-only header wordmarks shown in the launcher carousel
when the UI language is Korean (curr_lang->codepage == 949). English/other
languages keep the existing English header images.

Usage:
  python3 tools/gen_korean_logos.py <YeonSung-Regular.ttf> <out.c> [--preview out.png]
"""
import argparse
from PIL import Image, ImageFont, ImageDraw

# (struct_name, korean_text). Order here = append order in rg_logos.c and must
# match the order the RG_LOGO_HEADER_*_KO enums are appended in bitmaps.h.
# Consoles with no natural Korean name (MSX, SG-1000, Atari 2600/7800,
# Amstrad, PICO-8) are intentionally omitted — they keep their English header.
NAMES = [
    ("header_nes_ko",      "패미컴"),
    ("header_gb_ko",       "게임보이"),
    ("header_gbc_ko",      "게임보이 컬러"),
    ("header_gw_ko",       "게임&워치"),
    ("header_pce_ko",      "PC엔진"),
    ("header_gg_ko",       "게임기어"),
    ("header_sms_ko",      "마스터시스템"),
    ("header_gen_ko",      "메가드라이브"),
    ("header_col_ko",      "콜레코비전"),
    ("header_wsv_ko",      "슈퍼비전"),
    ("header_ngp_ko",      "네오지오 포켓"),
    ("header_wswan_ko",    "원더스완"),
    ("header_lynx_ko",     "링스"),
    ("header_tama_ko",     "다마고치"),
    ("header_pkmini_ko",   "포켓몬 미니"),
    ("header_homebrew_ko", "홈브루"),
]

TARGET_H = 18      # final glyph image height (matches existing headers)
FONT_PX  = 24      # render size before crop; cropped+scaled to TARGET_H
THRESHOLD = 110    # grayscale -> 1-bit cutoff (visible if brighter)


def render_text(font, text):
    # Render white text on black, oversized, then crop to ink bbox.
    pad = 8
    tmp = Image.new("L", (font.getlength(text).__ceil__() + pad * 2, FONT_PX * 3), 0)
    d = ImageDraw.Draw(tmp)
    d.text((pad, pad), text, font=font, fill=255)
    bbox = tmp.getbbox()
    if bbox is None:
        raise ValueError(f"empty render for {text!r}")
    glyph = tmp.crop(bbox)
    # Scale to target height preserving aspect.
    w = max(1, round(glyph.width * TARGET_H / glyph.height))
    glyph = glyph.resize((w, TARGET_H), Image.Resampling.LANCZOS)
    return glyph


def pack_1bpp(img):
    width, height = img.size
    padded_w = ((width + 7) // 8) * 8
    px = img.load()
    rows = []
    for y in range(height):
        row = []
        for xb in range(0, padded_w, 8):
            byte = 0
            for bit in range(8):
                x = xb + bit
                if x < width and px[x, y] >= THRESHOLD:
                    byte |= 1 << (7 - bit)
            row.append(byte)
        rows.append(row)
    return padded_w, height, rows


def emit_struct(name, padded_w, height, rows):
    out = [f"const retro_logo_image {name} LOGO_DATA = {{", f"    {padded_w},", f"    {height},", "    {"]
    for row in rows:
        hexv = ", ".join(f"0x{b:02x}" for b in row)
        visual = "".join("#" if (b >> (7 - i)) & 1 else "_" for b in row for i in range(8))
        out.append(f"        {hexv},  //  {visual}")
    out.append("    },")
    out.append("};")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("font")
    ap.add_argument("out_c")
    ap.add_argument("--preview")
    args = ap.parse_args()

    font = ImageFont.truetype(args.font, FONT_PX)
    structs, glyphs = [], []
    for name, text in NAMES:
        g = render_text(font, text)
        pw, h, rows = pack_1bpp(g)
        structs.append(emit_struct(name, pw, h, rows))
        glyphs.append((name, text, g, pw))
        print(f"{name:20s} {text:8s} -> {pw}x{h}")

    header = ("// AUTO-GENERATED by tools/gen_korean_logos.py (Yeon Sung font).\n"
              "// Korean-only console name headers. Do not edit by hand.\n")
    with open(args.out_c, "w") as f:
        f.write(header + "\n" + "\n\n".join(structs) + "\n")
    print(f"wrote {args.out_c}")

    if args.preview:
        # Stack the 1-bit glyphs (rendered white-on-dark) for a visual check.
        gap = 6
        W = max(pw for *_ , pw in glyphs) + 8
        H = sum(g.height for _, _, g, _ in glyphs) + gap * len(glyphs) + 8
        canvas = Image.new("L", (W, H), 30)
        y = 4
        for name, text, g, pw in glyphs:
            # binarize the same way the firmware sees it
            bw = g.point(lambda v: 255 if v >= THRESHOLD else 0)
            canvas.paste(bw, (4, y))
            y += g.height + gap
        canvas.resize((W * 3, H * 3), Image.Resampling.NEAREST).save(args.preview)
        print(f"wrote preview {args.preview}")


if __name__ == "__main__":
    main()
