#!/usr/bin/env python3
"""Render RomM platform device icons (SVG) to PALETTED RGB565 C data for the
launcher header console icon. The LCD is RGB565, so these show in full colour.

To keep internal flash small, each icon is quantised to <=15 colours and
packed 4bpp (2 px/byte): a 16-entry uint16 RGB565 palette + a nibble index
array. Palette index 0 is the transparent colour key (skipped at blit time).
~0.5 KB/icon vs ~2 KB for raw RGB565.

  python3 tools/gen_color_icons.py <romm_svg_dir> <out.inc>
"""
import sys, os, cairosvg
from PIL import Image

H = 32  # banner height

# RG_LOGO_PAD_* enum  ->  RomM platform slug
MAP = [
    ("RG_LOGO_PAD_NES",     "nes"),
    ("RG_LOGO_PAD_GB",      "gb"),
    ("RG_LOGO_PAD_GG",      "gamegear"),
    ("RG_LOGO_PAD_PCE",     "tg16"),
    ("RG_LOGO_PAD_GEN",     "genesis"),
    ("RG_LOGO_PAD_COL",     "colecovision"),
    ("RG_LOGO_PAD_A2600",   "atari2600"),
    ("RG_LOGO_PAD_A7800",   "atari7800"),
    ("RG_LOGO_PAD_AMSTRAD", "acpc"),
    ("RG_LOGO_PAD_NGP",     "neo-geo-pocket"),
    ("RG_LOGO_PAD_WSWAN",   "wonderswan"),
]


def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def render(svg_dir, slug):
    png = os.path.join(svg_dir, slug + ".png")
    cairosvg.svg2png(url=os.path.join(svg_dir, slug + ".svg"), write_to=png, output_height=H * 4)
    im = Image.open(png).convert("RGBA")
    w = max(1, round(im.width * H / im.height))
    im = im.resize((w, H), Image.LANCZOS)

    alpha = im.getchannel("A")
    # Quantise opaque colours to 15 (palette indices become 1..15; 0=transparent)
    q = im.convert("RGB").quantize(colors=15, method=Image.Quantize.FASTOCTREE)
    qp = q.getpalette()  # [r,g,b, r,g,b, ...]
    pal = [0]  # index 0 = transparent
    for i in range(15):
        r, g, b = qp[i * 3], qp[i * 3 + 1], qp[i * 3 + 2]
        pal.append(to565(r, g, b))
    while len(pal) < 16:
        pal.append(0)

    qpx = q.load()
    apx = alpha.load()
    idx = []
    for y in range(H):
        for x in range(w):
            idx.append(0 if apx[x, y] < 96 else (qpx[x, y] + 1))
    # pack 4bpp, flat, 2 px/byte (even px -> high nibble)
    data = []
    for i in range(0, len(idx), 2):
        hi = idx[i] & 0xF
        lo = idx[i + 1] & 0xF if i + 1 < len(idx) else 0
        data.append((hi << 4) | lo)
    return w, H, pal, data


def main():
    svg_dir, out = sys.argv[1], sys.argv[2]
    chunks, table = [], []
    total = 0
    for enum, slug in MAP:
        w, h, pal, data = render(svg_dir, slug)
        var = "cicon_" + slug.replace("-", "_")
        pbody = ",".join(f"0x{v:04x}" for v in pal)
        dbody = ",".join(f"0x{v:02x}" for v in data)
        chunks.append(f"static const uint16_t {var}_pal[16] = {{{pbody}}};")
        chunks.append(f"static const uint8_t {var}_data[{len(data)}] = {{{dbody}}};")
        chunks.append(f"const color_icon_t {var} = {{ {w}, {h}, {var}_pal, {var}_data }};")
        table.append((enum, var))
        total += len(data) + 32
        print(f"{enum:22s} {slug:16s} {w}x{h}  {len(data)+32}B")
    sw = "\n".join(f"        case {e}: return &{v};" for e, v in table)
    func = (f"\nconst color_icon_t *color_icon_for_logo(int16_t logo_idx)\n{{\n"
            f"    switch (logo_idx) {{\n{sw}\n        default: return (const color_icon_t *)0;\n    }}\n}}\n")
    with open(out, "w") as f:
        f.write("/* AUTO-GENERATED by tools/gen_color_icons.py — RomM device icons, 4bpp palette. */\n\n")
        f.write("\n".join(chunks) + "\n" + func)
    print(f"wrote {out}  (~{total}B icon data total)")


if __name__ == "__main__":
    main()
