#!/usr/bin/env python3
"""Render RomM platform device icons (SVG) to full-color RGB565 C arrays for
the launcher header-right console icon. The LCD is RGB565, so these display
in full colour (unlike the 1-bit retro_logo_image pad_* icons).

Transparent pixels are written as a colour key (0xF81F magenta) and skipped
at blit time. Output: appended to rg_logos.c, with a color_icon_for_logo()
lookup keyed by the RG_LOGO_PAD_* index.

  python3 tools/gen_color_icons.py <romm_svg_dir> <out.inc>
"""
import sys, os, cairosvg
from PIL import Image

H = 32                 # banner height
KEY = 0xF81F           # transparent colour key (magenta)

# RG_LOGO_PAD_* enum  ->  RomM platform slug
MAP = [
    ("RG_LOGO_PAD_NES",     "nes"),
    ("RG_LOGO_PAD_GB",      "gb"),
    ("RG_LOGO_PAD_GG",      "gamegear"),
    ("RG_LOGO_PAD_PCE",     "tg16"),
    ("RG_LOGO_PAD_GEN",     "genesis"),
    ("RG_LOGO_PAD_COL",     "colecovision"),
    ("RG_LOGO_PAD_A2600",   "atari2600"),
    ("RG_LOGO_PAD_A7800",   "atari7800"),
    ("RG_LOGO_PAD_AMSTRAD", "acpc"),
    ("RG_LOGO_PAD_NGP",     "neo-geo-pocket"),
    ("RG_LOGO_PAD_WSWAN",   "wonderswan"),
]


def to565(r, g, b):
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def render(svg_dir, slug):
    png = os.path.join(svg_dir, slug + ".png")
    cairosvg.svg2png(url=os.path.join(svg_dir, slug + ".svg"), write_to=png, output_height=H * 4)
    im = Image.open(png).convert("RGBA")
    w = max(1, round(im.width * H / im.height))
    im = im.resize((w, H), Image.LANCZOS)
    px = im.load()
    data = []
    for y in range(H):
        for x in range(w):
            r, g, b, a = px[x, y]
            data.append(KEY if a < 96 else to565(r, g, b))
    return w, H, data


def main():
    svg_dir, out = sys.argv[1], sys.argv[2]
    chunks, table = [], []
    for enum, slug in MAP:
        w, h, data = render(svg_dir, slug)
        var = "cicon_" + slug.replace("-", "_")
        body = ",".join(f"0x{v:04x}" for v in data)
        chunks.append(f"static const uint16_t {var}_data[{len(data)}] = {{{body}}};")
        chunks.append(f"const color_icon_t {var} = {{ {w}, {h}, {var}_data }};")
        table.append((enum, var))
        print(f"{enum:22s} {slug:16s} {w}x{h}")
    sw = "\n".join(f"        case {e}: return &{v};" for e, v in table)
    func = (f"\nconst color_icon_t *color_icon_for_logo(int16_t logo_idx)\n{{\n"
            f"    switch (logo_idx) {{\n{sw}\n        default: return (const color_icon_t *)0;\n    }}\n}}\n")
    with open(out, "w") as f:
        f.write("/* AUTO-GENERATED by tools/gen_color_icons.py — RomM device icons, RGB565. */\n\n")
        f.write("\n".join(chunks) + "\n" + func)
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
