#!/usr/bin/env python3
"""Pick the 68K opcode handlers that ride ITCM in the Sega CD core.

    segacd_itc_gen.py <profile_dir> [budget_kb] > Core/Src/porting/segacd/segacd_itc_ops.ld

<profile_dir> holds one sub-directory per game, each with a `calls` file: the
`calls name` pairs of `gprof -b -p` over the host rig built with -pg (see
docs/HARNESSES.md, Sega CD). Every game is normalised to one, so a long boot
loop cannot outvote the rest of the library, then handlers are taken in
descending share until their object-file sizes reach the budget.

Why a list at all: famec compiles 1,952 handlers (177 KB), far past ITCM, yet
751 of them ever run across the 15-game library and the hottest 24 KB cover
99.7% of executions (99.4% in the worst game). The output is committed, so a
build never depends on having run the profile.
"""
import collections
import pathlib
import subprocess
import sys

FAMEC_OBJ = "build/segacd/cpu__fame__famec.o"


def handler_sizes():
    out = subprocess.run(["arm-none-eabi-objdump", "-h", FAMEC_OBJ],
                         capture_output=True, text=True, check=True).stdout
    sizes = {}
    for line in out.splitlines():
        f = line.split()
        if len(f) >= 3 and f[1].startswith(".text.OP_0x"):
            sizes[f[1][len(".text."):]] = int(f[2], 16)
    return sizes


def library_share(profile_dir):
    total = collections.Counter()
    games = 0
    for calls in sorted(pathlib.Path(profile_dir).glob("*/calls")):
        counts = {}
        for line in calls.read_text().splitlines():
            n, name = line.split()
            if name.startswith("OP_0x"):
                counts[name] = int(n)
        s = sum(counts.values())
        if s:
            games += 1
            total.update({k: v / s for k, v in counts.items()})
    return total, games


def main():
    profile_dir = sys.argv[1]
    budget = int(sys.argv[2] if len(sys.argv) > 2 else 24) * 1024
    sizes = handler_sizes()
    share, games = library_share(profile_dir)
    if not games:
        sys.exit(f"no */calls files under {profile_dir}")
    picked, used, covered = [], 0, 0.0
    for name, s in share.most_common():
        size = sizes.get(name)
        if size is None or used + size > budget:
            continue
        picked.append(name)
        used += size
        covered += s
    print(f"/* Generated by tools/segacd_itc_gen.py from {games} games: {len(picked)} handlers,")
    print(f"   {used} bytes, {100 * covered / sum(share.values()):.2f}% of 68K opcode executions. */")
    print(f"{FAMEC_OBJ} (")
    for name in picked:
        print(f"  .text.{name}")
    print(")")


if __name__ == "__main__":
    main()
