#include "cps1_core.h"
#include "cps1_cpu68k.h"
#include "cps1_ppu.h"
#include "cps1_rom.h"

/* Core/Src/porting/cps1/cps1_rc_generated.c -- auto-generated by
 * tools/cps1_recompiler/translate.py from s_cpu_test_program below. Runs
 * the SAME program as the interpreter but via emitted C (goto-threaded
 * basic blocks) instead of fetch/decode/execute, so CPS1_ENGINE_RECOMPILER
 * is a genuinely different code path from CPS1_ENGINE_INTERPRETER -- the
 * interpreter-vs-recompiler diff this whole harness exists for is real now,
 * not two copies of the same stub. Regenerate with
 * tools/cps1_recompiler/selftest.sh if s_cpu_test_program ever changes. */
void cps1_rc_translated(cps1_cpu68k_t *regs);

/*
 * TODO(cps1): CPS1_ENGINE_INTERPRETER should become the real 68000+Z80
 * interpreter and PPU renderer; CPS1_ENGINE_RECOMPILER the static
 * recompiler's translated output (docs/CPS1_ULTIMATE_PORTING_PLAN.md
 * technique 1 / tools/cps1_recompiler/translate.py). Until the recompiler
 * exists, both engines drive the identical cps1_cpu68k interpreter, so a
 * passing interpreter-vs-recompiler diff only proves the harness compares
 * correctly -- it proves nothing about emulation correctness. The
 * framebuffer is now rendered by the real OAM-prescan -> tile-cache ->
 * palette pipeline in cps1_ppu.c, but against a synthetic ROM/OAM/palette
 * (s_synthetic_* below) -- there is still no real CPS-1 ROM, so this
 * proves the pipeline wiring, not that any real game's graphics decode
 * correctly (see cps1_rom_decode_tile's bitplane-interleave caveat).
 *
 * s_cpu_test_program is hand-assembled 68000 code (no ROM-loading format
 * exists yet -- see docs/CPS1_FEASIBILITY.md section 6):
 *   MOVEQ #10,D0
 *   MOVEQ #0,D1
 *   loop:    ADDQ #3,D1
 *            DBRA D0,loop
 *   RTS
 * Expected end state: D1 = 33 (11 iterations x 3), D0 = 0x0000FFFF (DBcc
 * only touches the low word), halted = 1.
 */
static const uint8_t s_cpu_test_program[] = {
    0x70, 0x0A, /* MOVEQ #10,D0        */
    0x72, 0x00, /* MOVEQ #0,D1         */
    0x56, 0x81, /* loop: ADDQ #3,D1    */
    0x51, 0xC8, /* DBRA D0,loop        */
    0xFF, 0xFC, /* displacement = -4   */
    0x4E, 0x75, /* RTS                 */
};

#define CPS1_CPU_MAX_STEPS_PER_FRAME 64

/*
 * Synthetic PPU test scene -- no real CPS-1 GFX ROM exists yet, so this
 * stands in for one: CPS1_SYN_TILE_COUNT tiles with a formulaic diagonal-
 * stripe index pattern (deterministic, not hand-authored art), tiled across
 * a CPS1_SYN_OAM_COLS x CPS1_SYN_OAM_ROWS grid of 8x8 sprites (224 <=
 * CPS1_OAM_MAX_SPRITES). Shared by both engines since the PPU isn't driven
 * by CPU state yet -- see the TODO above.
 */
#define CPS1_SYN_TILE_COUNT 4
#define CPS1_SYN_OAM_COLS   16
#define CPS1_SYN_OAM_ROWS   14

static uint8_t s_synthetic_gfx[CPS1_SYN_TILE_COUNT * CPS1_TILE_SIZE_BYTES];
static cps1_rom_t s_synthetic_rom;
static cps1_oam_t s_synthetic_oam;
static cps1_palette_t s_synthetic_palette;
static cps1_tile_cache_t s_tile_cache;
static int s_ppu_initialized;

static void cps1_ppu_init_synthetic(void)
{
    if (s_ppu_initialized)
        return;
    s_ppu_initialized = 1;

    for (unsigned t = 0; t < CPS1_SYN_TILE_COUNT; t++) {
        for (int row = 0; row < 8; row++) {
            for (int pair = 0; pair < 4; pair++) {
                uint8_t idx_hi = (uint8_t)((row + pair * 2 + t) % 4);
                uint8_t idx_lo = (uint8_t)((row + pair * 2 + 1 + t) % 4);
                s_synthetic_gfx[t * CPS1_TILE_SIZE_BYTES + row * 4 + pair] =
                    (uint8_t)((idx_hi << 4) | idx_lo);
            }
        }
    }

    cps1_rom_region_t gfx_region = { s_synthetic_gfx, sizeof(s_synthetic_gfx) };
    cps1_rom_region_t prg_region = { s_cpu_test_program, sizeof(s_cpu_test_program) };
    cps1_rom_region_t empty = { 0, 0 };
    cps1_rom_attach(&s_synthetic_rom, prg_region, gfx_region, empty, empty);

    for (int b = 0; b < CPS1_PALETTE_BANKS; b++)
        for (int c = 0; c < CPS1_PALETTE_COLORS; c++)
            s_synthetic_palette.colors[b][c] = 0;
    s_synthetic_palette.colors[0][1] = 0xF800; /* red   */
    s_synthetic_palette.colors[0][2] = 0x07E0; /* green */
    s_synthetic_palette.colors[0][3] = 0x001F; /* blue  */

    s_synthetic_oam.count = CPS1_SYN_OAM_COLS * CPS1_SYN_OAM_ROWS;
    for (int r = 0; r < CPS1_SYN_OAM_ROWS; r++) {
        for (int c = 0; c < CPS1_SYN_OAM_COLS; c++) {
            cps1_oam_entry_t *s = &s_synthetic_oam.sprites[r * CPS1_SYN_OAM_COLS + c];
            s->x = (int16_t)(c * 8);
            s->y = (int16_t)(r * 8);
            s->tile_index = (uint16_t)((r + c) % CPS1_SYN_TILE_COUNT);
            s->attr = 0;
            s->enabled = 1;
        }
    }

    cps1_tile_cache_reset(&s_tile_cache);
}

typedef struct {
    uint16_t fb[CPS1_FB_WIDTH * CPS1_FB_HEIGHT];
    uint32_t frame;
    cps1_cpu68k_t cpu;
} cps1_engine_state_t;

static cps1_engine_state_t s_engine[CPS1_ENGINE_COUNT];

void cps1_core_reset(cps1_engine_kind_t engine)
{
    cps1_engine_state_t *e = &s_engine[engine];
    e->frame = 0;
    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++)
        e->fb[i] = 0;
    cps1_cpu68k_reset(&e->cpu, s_cpu_test_program, sizeof(s_cpu_test_program));
}

void cps1_core_run_frame(cps1_engine_kind_t engine)
{
    cps1_engine_state_t *e = &s_engine[engine];
    e->frame++;

    if (engine == CPS1_ENGINE_RECOMPILER) {
        if (!e->cpu.halted)
            cps1_rc_translated(&e->cpu);
    } else {
        cps1_cpu68k_run(&e->cpu, CPS1_CPU_MAX_STEPS_PER_FRAME);
    }

    cps1_ppu_init_synthetic();
    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++)
        e->fb[i] = 0;
    cps1_ppu_render(&s_synthetic_oam, &s_synthetic_rom, &s_tile_cache, &s_synthetic_palette, e->fb);
}

const uint16_t *cps1_core_get_framebuffer(cps1_engine_kind_t engine)
{
    return s_engine[engine].fb;
}

uint32_t cps1_core_checksum(cps1_engine_kind_t engine)
{
    const uint16_t *fb = s_engine[engine].fb;
    uint32_t h = 2166136261u;
    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++) {
        h ^= fb[i];
        h *= 16777619u;
    }
    return h;
}

uint32_t cps1_core_cpu_state_hash(cps1_engine_kind_t engine)
{
    return cps1_cpu68k_state_hash(&s_engine[engine].cpu);
}

uint32_t cps1_core_cpu_illegal_count(cps1_engine_kind_t engine)
{
    return s_engine[engine].cpu.illegal_count;
}
