/* Auto-generated by tools/cps1_recompiler/translate.py -- DO NOT EDIT BY HAND. */
#include "cps1_cpu68k.h"
#include "cps1_rc_runtime.h"

void cps1_rc_translated(cps1_cpu68k_t *regs)
{
    /* 0x000000: MOVEQ #10,D0 */
    regs->d[0] = (uint32_t)(int32_t)(10);
    cps1_rc_set_nz_flags(regs, (int32_t)(10));
    regs->pc = 0x000002u; regs->cycles += 4;
    /* 0x000002: MOVEQ #0,D1 */
    regs->d[1] = (uint32_t)(int32_t)(0);
    cps1_rc_set_nz_flags(regs, (int32_t)(0));
    regs->pc = 0x000004u; regs->cycles += 4;
L000004: ;
    /* 0x000004: ADDQ #3,D1 */
    cps1_rc_add(regs, 1, 3u, 2);
    regs->pc = 0x000006u; regs->cycles += 4;
    /* 0x000006: DBF D0,L000004 */
    if (!cps1_rc_cc_F(regs)) {
        uint16_t lo = (uint16_t)((regs->d[0] & 0xFFFF) - 1);
        regs->d[0] = (regs->d[0] & 0xFFFF0000u) | lo;
        if (lo != 0xFFFFu) {
            regs->pc = 0x000004u; regs->cycles += 10;
            goto L000004;
        }
        regs->pc = 0x00000Au; regs->cycles += 14;
    } else {
        regs->pc = 0x00000Au; regs->cycles += 10;
    }
    /* 0x00000A: RTS */
    regs->pc = 0x00000Cu; regs->cycles += 16;
    regs->halted = 1;
    return;
    return;
}
