#include <stddef.h>

#include "cps1_core.h"
#include "cps1_cpu68k.h"
#include "cps1_ppu.h"
#include "cps1_rom.h"
#include "cps1_sound_hle.h"
#include "cps1_bg.h"

/* Core/Src/porting/cps1/cps1_rc_generated.c -- auto-generated by
 * tools/cps1_recompiler/translate.py from s_cpu_test_program below. Runs
 * the SAME program as the interpreter but via emitted C (goto-threaded
 * basic blocks) instead of fetch/decode/execute, so CPS1_ENGINE_RECOMPILER
 * is a genuinely different code path from CPS1_ENGINE_INTERPRETER -- the
 * interpreter-vs-recompiler diff this whole harness exists for is real now,
 * not two copies of the same stub. Regenerate with
 * tools/cps1_recompiler/selftest.sh if s_cpu_test_program ever changes. */
void cps1_rc_translated(cps1_cpu68k_t *regs);

/*
 * TODO(cps1): CPS1_ENGINE_INTERPRETER should become the real 68000+Z80
 * interpreter and PPU renderer; CPS1_ENGINE_RECOMPILER the static
 * recompiler's translated output (docs/CPS1_ULTIMATE_PORTING_PLAN.md
 * technique 1 / tools/cps1_recompiler/translate.py). Until the recompiler
 * exists, both engines drive the identical cps1_cpu68k interpreter, so a
 * passing interpreter-vs-recompiler diff only proves the harness compares
 * correctly -- it proves nothing about emulation correctness. The
 * framebuffer is now rendered by the real OAM-prescan -> tile-cache ->
 * palette pipeline in cps1_ppu.c, but against a synthetic ROM/OAM/palette
 * (s_synthetic_* below) -- there is still no real CPS-1 ROM, so this
 * proves the pipeline wiring, not that any real game's graphics decode
 * correctly (see cps1_rom_decode_tile's bitplane-interleave caveat).
 *
 * s_cpu_test_program is hand-assembled 68000 code (no ROM-loading format
 * exists yet -- see docs/CPS1_FEASIBILITY.md section 6):
 *   MOVEQ #10,D0
 *   MOVEQ #0,D1
 *   loop:    ADDQ #3,D1
 *            DBRA D0,loop
 *   RTS
 * Expected end state: D1 = 33 (11 iterations x 3), D0 = 0x0000FFFF (DBcc
 * only touches the low word), halted = 1.
 */
static const uint8_t s_cpu_test_program[] = {
    0x70, 0x0A, /* MOVEQ #10,D0        */
    0x72, 0x00, /* MOVEQ #0,D1         */
    0x56, 0x81, /* loop: ADDQ #3,D1    */
    0x51, 0xC8, /* DBRA D0,loop        */
    0xFF, 0xFC, /* displacement = -4   */
    0x4E, 0x75, /* RTS                 */
};

#define CPS1_CPU_MAX_STEPS_PER_FRAME 64

/*
 * Synthetic PPU test scene -- no real CPS-1 GFX ROM exists yet, so this
 * stands in for one: CPS1_SYN_TILE_COUNT tiles with a formulaic diagonal-
 * stripe index pattern (deterministic, not hand-authored art), tiled across
 * a CPS1_SYN_OAM_COLS x CPS1_SYN_OAM_ROWS grid of 8x8 sprites (224 <=
 * CPS1_OAM_MAX_SPRITES). Shared by both engines since the PPU isn't driven
 * by CPU state yet -- see the TODO above.
 */
#define CPS1_SYN_TILE_COUNT 4  /* distinct patterns a cell/sprite index picks from */
#define CPS1_SYN_OAM_COLS   16
#define CPS1_SYN_OAM_ROWS   14

/* The underlying gfx blob must be bigger than CPS1_SYN_TILE_COUNT: SCROLL2/
 * SCROLL3 cells fetch base_tile_index + up to 15 (4x4 sub-tiles, see
 * cps1_bg_render_layer), so a buffer sized to only the 4 "logical" patterns
 * would make most BG sub-tile fetches silently miss (out of range -> NULL
 * -> skipped), under-costing the profiling run relative to a real ROM where
 * they'd all decode. 32 comfortably covers base 0..3 + offset 0..15. */
#define CPS1_SYN_GFX_TILE_COUNT 32

static uint8_t s_synthetic_gfx[CPS1_SYN_GFX_TILE_COUNT * CPS1_TILE_SIZE_BYTES];
static cps1_rom_t s_synthetic_rom;
static cps1_oam_t s_synthetic_oam;
static cps1_palette_t s_synthetic_palette;
static cps1_tile_cache_t s_tile_cache;
static int s_ppu_initialized;

static void cps1_ppu_init_synthetic(void)
{
    if (s_ppu_initialized)
        return;
    s_ppu_initialized = 1;

    for (unsigned t = 0; t < CPS1_SYN_GFX_TILE_COUNT; t++) {
        for (int row = 0; row < 8; row++) {
            for (int pair = 0; pair < 4; pair++) {
                uint8_t idx_hi = (uint8_t)((row + pair * 2 + t) % 4);
                uint8_t idx_lo = (uint8_t)((row + pair * 2 + 1 + t) % 4);
                s_synthetic_gfx[t * CPS1_TILE_SIZE_BYTES + row * 4 + pair] =
                    (uint8_t)((idx_hi << 4) | idx_lo);
            }
        }
    }

    cps1_rom_region_t gfx_region = { s_synthetic_gfx, sizeof(s_synthetic_gfx) };
    cps1_rom_region_t prg_region = { s_cpu_test_program, sizeof(s_cpu_test_program) };
    cps1_rom_region_t empty = { 0, 0 };
    cps1_rom_attach(&s_synthetic_rom, prg_region, gfx_region, empty, empty);

    for (int b = 0; b < CPS1_PALETTE_BANKS; b++)
        for (int c = 0; c < CPS1_PALETTE_COLORS; c++)
            s_synthetic_palette.colors[b][c] = 0;
    s_synthetic_palette.colors[0][1] = 0xF800; /* red   */
    s_synthetic_palette.colors[0][2] = 0x07E0; /* green */
    s_synthetic_palette.colors[0][3] = 0x001F; /* blue  */

    s_synthetic_oam.count = CPS1_SYN_OAM_COLS * CPS1_SYN_OAM_ROWS;
    for (int r = 0; r < CPS1_SYN_OAM_ROWS; r++) {
        for (int c = 0; c < CPS1_SYN_OAM_COLS; c++) {
            cps1_oam_entry_t *s = &s_synthetic_oam.sprites[r * CPS1_SYN_OAM_COLS + c];
            s->x = (int16_t)(c * 8);
            s->y = (int16_t)(r * 8);
            s->tile_index = (uint16_t)((r + c) % CPS1_SYN_TILE_COUNT);
            s->attr = 0;
            s->enabled = 1;
        }
    }

    cps1_tile_cache_reset(&s_tile_cache);
}

/*
 * Synthetic BG scroll layers -- fills the whole 64x64 map of all three
 * layers (SCROLL1/2/3) with a cycling pattern so scrolling later reveals
 * real content everywhere, not just a hand-placed few cells. tile_index
 * cycles through CPS1_SYN_TILE_COUNT logical patterns; each layer gets its
 * own palette bank (3/4/5) so the composited result visibly separates
 * bottom/middle/top (see cps1-bg-selftest for the priority proof; this is
 * the full-frame integration of the same mechanism).
 */
static cps1_bg_state_t s_bg;
static int s_bg_initialized;

static void cps1_bg_init_synthetic(void)
{
    if (s_bg_initialized)
        return;
    s_bg_initialized = 1;

    cps1_bg_reset(&s_bg);

    static const uint16_t bg_colors[CPS1_BG_LAYER_COUNT] = { 0xAD55, 0xFD20, 0x87F0 };
    for (unsigned l = 0; l < CPS1_BG_LAYER_COUNT; l++) {
        s_synthetic_palette.colors[3 + l][1] = bg_colors[l];
        for (int cy = 0; cy < CPS1_BG_MAP_H; cy++) {
            for (int cx = 0; cx < CPS1_BG_MAP_W; cx++) {
                cps1_bg_cell_t *cell = &s_bg.layers[l].cells[cy * CPS1_BG_MAP_W + cx];
                cell->tile_index = (uint16_t)((cx + cy) % CPS1_SYN_TILE_COUNT);
                cell->palette = (uint8_t)(3 + l);
                cell->enabled = 1;
            }
        }
    }
}

/*
 * Sound HLE (docs/CPS1_SENIOR_TRICKS_ANALYSIS.md cheat A): no Z80, no
 * YM2151 -- s_sound is the native C mixer from cps1_sound_hle.c, and the
 * 68000 reaches it only through the bus write intercept below
 * (CPS1_SOUND_CMD_BASE), the same way a real 68000 would only ever reach
 * the Z80 through a shared command latch.
 */
static cps1_sound_hle_t s_sound;
static const int8_t s_synthetic_oki_sample[8] = { 20, -20, 40, -40, 60, -60, 30, -30 };
static int s_sound_initialized;

static void cps1_sound_init_synthetic(void)
{
    if (s_sound_initialized)
        return;
    s_sound_initialized = 1;

    cps1_sound_hle_reset(&s_sound);
    cps1_sound_hle_attach_oki_sample(&s_sound, s_synthetic_oki_sample,
                                      sizeof(s_synthetic_oki_sample));
}

/*
 * 68000 <-> VDP memory bus -- Phase 9: real memory map
 * (docs/CPS1_MAME_ALIGNMENT.md sections 3/4/9). WRAM stays a fixed 64KB
 * region (that address was already correct from Phase 7). OBJ/SCROLL1/2/3/
 * PALETTE are no longer separate fixed regions -- they are all VIEWS into
 * one shared 192KB gfxram pool, at offsets the CPS-A registers (0x800100-
 * 0x80013F) specify, exactly like real hardware's cps1_base()
 * (base = reg*256, masked to a boundary, clamped into gfxram). A 68000
 * write to a gfxram address is routed to whichever parsed view CURRENTLY
 * claims that address (recomputed from the CURRENT register values on
 * every write, not cached) -- so moving a base register genuinely
 * relocates where subsequent writes land, the same as on real hardware.
 */
#define CPS1_WRAM_BASE 0xFF0000u
#define CPS1_WRAM_SIZE 0x10000u

#define CPS1_GFXRAM_BASE 0x900000u
#define CPS1_GFXRAM_SIZE 0x30000u /* 192KB, matches the real qsound_main_map region */

#define CPS1_CPSA_BASE  0x800100u
#define CPS1_CPSA_SIZE  0x40u /* 32 words, 0x800100-0x80013F */
#define CPS1_CPSA_COUNT (CPS1_CPSA_SIZE / 2u)

/* Word offsets within the CPS-A register block, per
 * docs/CPS1_MAME_ALIGNMENT.md section 4 (cps1.h:172-193). Only the base
 * registers this phase wires up are named as enums the code branches on;
 * unlisted offsets (OTHER_BASE, stars, rowscroll, videocontrol) are still
 * stored in s_cps_a_regs but nothing reads them yet -- same "stored but
 * inert until something consumes it" status real unused registers have. */
enum {
    CPS1_REG_OBJ_BASE        = 0x00 / 2,
    CPS1_REG_SCROLL1_BASE    = 0x02 / 2,
    CPS1_REG_SCROLL2_BASE    = 0x04 / 2,
    CPS1_REG_SCROLL3_BASE    = 0x06 / 2,
    CPS1_REG_OTHER_BASE      = 0x08 / 2,
    CPS1_REG_PALETTE_BASE    = 0x0A / 2,
    CPS1_REG_SCROLL1_SCROLLX = 0x0C / 2,
    CPS1_REG_SCROLL1_SCROLLY = 0x0E / 2,
    CPS1_REG_SCROLL2_SCROLLX = 0x10 / 2,
    CPS1_REG_SCROLL2_SCROLLY = 0x12 / 2,
    CPS1_REG_SCROLL3_SCROLLX = 0x14 / 2,
    CPS1_REG_SCROLL3_SCROLLY = 0x16 / 2,
};

/* Sound command latch: moved OUT of the gfxram range it previously
 * (incorrectly) overlapped in Phase 6/7. 0x800180 matches the real
 * non-QSound soundlatch address (docs/CPS1_MAME_ALIGNMENT.md section 4) --
 * Tenchi wo Kurau II itself uses QSound's shared-RAM protocol instead
 * (section 6), which is a later phase; this address is still real, just
 * for a different CPS-1 title's sound path, and doesn't collide with
 * anything now that gfxram has its own real range. */
#define CPS1_SOUND_CMD_BASE 0x800180u

/* Base-register boundary mask: real hardware masks each base register to
 * a game-dependent boundary (m_scroll_size/m_obj_size, "typically 0x4000"
 * per the doc) -- using one boundary for every region is a documented
 * skeleton simplification, not a confirmed per-region value. */
#define CPS1_BASE_BOUNDARY 0x4000u

/* BG tilemap cell data size per layer: CPS1_BG_MAP_W*CPS1_BG_MAP_H cells,
 * 2 words (4 bytes) each -- word0=tile_index, word1 low byte=palette/high
 * byte=enabled. Scroll position is NOT part of this range any more (it's
 * the CPS1_REG_SCROLLn_SCROLLX/Y CPS-A registers instead, applied directly
 * in cps1_bus_write16's CPS-A branch). */
#define CPS1_BG_CELLS_BYTES ((uint32_t)CPS1_BG_MAP_W * CPS1_BG_MAP_H * 4u)

static uint8_t s_wram[CPS1_WRAM_SIZE];
static uint8_t s_gfxram[CPS1_GFXRAM_SIZE];
static uint16_t s_cps_a_regs[CPS1_CPSA_COUNT];
static int s_gfxram_initialized;

/* One-frame-delayed OBJ RAM (docs/CPS1_MAME_ALIGNMENT.md section 5,
 * cps1_objram_latch): s_synthetic_oam is what the CPU can see/write RIGHT
 * NOW; s_buffered_obj is what actually gets rendered, latched from
 * s_synthetic_oam once per frame (see cps1_core_run_frame's tail). */
static cps1_oam_t s_buffered_obj;

/* Default gfxram sub-offsets, applied at reset so the demo scene and
 * every existing selftest resolve to a sane, non-overlapping layout even
 * before any CPS-A register write -- arbitrary placeholders (documented
 * as such, like the boundary above), not confirmed per-game values. */
#define CPS1_DEFAULT_OBJ_OFFSET     0x00000u
#define CPS1_DEFAULT_SCROLL1_OFFSET 0x04000u
#define CPS1_DEFAULT_SCROLL2_OFFSET 0x08000u
#define CPS1_DEFAULT_SCROLL3_OFFSET 0x0C000u
#define CPS1_DEFAULT_OTHER_OFFSET   0x10000u
#define CPS1_DEFAULT_PALETTE_OFFSET 0x14000u

static void cps1_gfxram_init_synthetic(void)
{
    if (s_gfxram_initialized)
        return;
    s_gfxram_initialized = 1;

    /* Register value = desired_offset / 256 -- inverse of cps1_resolve_base
     * below, valid because every CPS1_DEFAULT_*_OFFSET here is already a
     * multiple of both 256 and CPS1_BASE_BOUNDARY. */
    s_cps_a_regs[CPS1_REG_OBJ_BASE]     = (uint16_t)(CPS1_DEFAULT_OBJ_OFFSET / 256u);
    s_cps_a_regs[CPS1_REG_SCROLL1_BASE] = (uint16_t)(CPS1_DEFAULT_SCROLL1_OFFSET / 256u);
    s_cps_a_regs[CPS1_REG_SCROLL2_BASE] = (uint16_t)(CPS1_DEFAULT_SCROLL2_OFFSET / 256u);
    s_cps_a_regs[CPS1_REG_SCROLL3_BASE] = (uint16_t)(CPS1_DEFAULT_SCROLL3_OFFSET / 256u);
    s_cps_a_regs[CPS1_REG_OTHER_BASE]   = (uint16_t)(CPS1_DEFAULT_OTHER_OFFSET / 256u);
    s_cps_a_regs[CPS1_REG_PALETTE_BASE] = (uint16_t)(CPS1_DEFAULT_PALETTE_OFFSET / 256u);
}

static uint32_t cps1_resolve_base(uint16_t reg_value)
{
    uint32_t base = (uint32_t)reg_value * 256u;
    base &= ~(CPS1_BASE_BOUNDARY - 1u);
    /* CPS1_GFXRAM_SIZE (192KB) is NOT a power of two, so `& (SIZE-1)` is
     * not a valid wrap/clamp here -- it silently corrupts any offset with
     * bit 0x10000 set (e.g. 0x14000 & 0x2FFFF == 0x04000). Modulo is the
     * correct operation regardless of whether SIZE is a power of two. */
    return base % CPS1_GFXRAM_SIZE;
}

static uint32_t cps1_obj_base_addr(void)
{
    return CPS1_GFXRAM_BASE + cps1_resolve_base(s_cps_a_regs[CPS1_REG_OBJ_BASE]);
}

static uint32_t cps1_scroll_base_addr(unsigned layer)
{
    return CPS1_GFXRAM_BASE +
           cps1_resolve_base(s_cps_a_regs[CPS1_REG_SCROLL1_BASE + layer]);
}

static uint32_t cps1_palette_base_addr(void)
{
    return CPS1_GFXRAM_BASE + cps1_resolve_base(s_cps_a_regs[CPS1_REG_PALETTE_BASE]);
}

static uint16_t cps1_bus_read16(uint32_t addr)
{
    if (addr >= CPS1_WRAM_BASE && addr < CPS1_WRAM_BASE + CPS1_WRAM_SIZE) {
        uint32_t off = addr - CPS1_WRAM_BASE;
        return (uint16_t)((s_wram[off] << 8) | s_wram[off + 1]);
    }
    if (addr >= CPS1_GFXRAM_BASE && addr < CPS1_GFXRAM_BASE + CPS1_GFXRAM_SIZE) {
        uint32_t off = addr - CPS1_GFXRAM_BASE;
        return (uint16_t)((s_gfxram[off] << 8) | s_gfxram[off + 1]);
    }
    if (addr + 1 < s_synthetic_rom.prg.size)
        return (uint16_t)((s_synthetic_rom.prg.data[addr] << 8) | s_synthetic_rom.prg.data[addr + 1]);
    return 0;
}

static void cps1_bus_write16(uint32_t addr, uint16_t val)
{
    if (addr >= CPS1_WRAM_BASE && addr < CPS1_WRAM_BASE + CPS1_WRAM_SIZE) {
        uint32_t off = addr - CPS1_WRAM_BASE;
        s_wram[off] = (uint8_t)(val >> 8);
        s_wram[off + 1] = (uint8_t)(val & 0xFFu);
        return;
    }

    if (addr >= CPS1_CPSA_BASE && addr < CPS1_CPSA_BASE + CPS1_CPSA_SIZE) {
        uint32_t word_idx = (addr - CPS1_CPSA_BASE) / 2u;
        if (word_idx < CPS1_CPSA_COUNT)
            s_cps_a_regs[word_idx] = val;
        /* Scroll position registers apply immediately: they don't gate a
         * gfxram view, they're consumed directly by the renderer. */
        for (unsigned layer = 0; layer < CPS1_BG_LAYER_COUNT; layer++) {
            if (word_idx == (uint32_t)(CPS1_REG_SCROLL1_SCROLLX + layer * 2))
                s_bg.layers[layer].scroll_x = (int16_t)val;
            if (word_idx == (uint32_t)(CPS1_REG_SCROLL1_SCROLLY + layer * 2))
                s_bg.layers[layer].scroll_y = (int16_t)val;
        }
        return;
    }

    if (addr == CPS1_SOUND_CMD_BASE) {
        cps1_sound_hle_trigger(&s_sound, (uint8_t)(val & 0xFFu));
        return;
    }

    if (addr >= CPS1_GFXRAM_BASE && addr < CPS1_GFXRAM_BASE + CPS1_GFXRAM_SIZE) {
        uint32_t off = addr - CPS1_GFXRAM_BASE;
        s_gfxram[off] = (uint8_t)(val >> 8);
        s_gfxram[off + 1] = (uint8_t)(val & 0xFFu);

        /* Route into whichever parsed view CURRENTLY claims this address
         * (base recomputed from the live CPS-A registers every write) --
         * a moved base register genuinely changes where this lands. */
        uint32_t obj_base = cps1_obj_base_addr();
        uint32_t obj_size = (uint32_t)s_synthetic_oam.count * 8u;
        if (addr >= obj_base && addr < obj_base + obj_size) {
            uint32_t word_idx = (addr - obj_base) / 2u;
            uint32_t entry = word_idx / 4u;
            uint32_t field = word_idx % 4u;
            cps1_oam_entry_t *s = &s_synthetic_oam.sprites[entry];
            switch (field) {
            case 0: s->y = (int16_t)val; break;
            case 1: s->tile_index = val; break;
            case 2: s->attr = (uint8_t)val; break;
            default: s->x = (int16_t)val; break;
            }
            return;
        }

        uint32_t pal_base = cps1_palette_base_addr();
        uint32_t pal_size = (uint32_t)CPS1_PALETTE_BANKS * CPS1_PALETTE_COLORS * 2u;
        if (addr >= pal_base && addr < pal_base + pal_size) {
            uint32_t word_idx = (addr - pal_base) / 2u;
            unsigned bank = word_idx / CPS1_PALETTE_COLORS;
            unsigned color = word_idx % CPS1_PALETTE_COLORS;
            s_synthetic_palette.colors[bank][color] = cps1_palette_build(val);
            return;
        }

        for (unsigned layer = 0; layer < CPS1_BG_LAYER_COUNT; layer++) {
            uint32_t base = cps1_scroll_base_addr(layer);
            if (addr >= base && addr < base + CPS1_BG_CELLS_BYTES) {
                uint32_t word_idx = (addr - base) / 2u;
                uint32_t cell = word_idx / 2u;
                uint32_t field = word_idx % 2u;
                cps1_bg_layer_t *L = &s_bg.layers[layer];
                if (field == 0) {
                    L->cells[cell].tile_index = val;
                } else {
                    L->cells[cell].palette = (uint8_t)(val & 0xFFu);
                    L->cells[cell].enabled = (uint8_t)((val >> 8) != 0);
                }
                return;
            }
        }

        return; /* plain gfxram byte, no region currently claims it */
    }

    /* PRG ROM / unmapped: writes are no-ops. */
}

static const cps1_bus_t s_bus = { cps1_bus_read16, cps1_bus_write16 };

typedef struct {
    uint16_t fb[CPS1_FB_WIDTH * CPS1_FB_HEIGHT];
    uint32_t frame;
    cps1_cpu68k_t cpu;
} cps1_engine_state_t;

static cps1_engine_state_t s_engine[CPS1_ENGINE_COUNT];

/* Host-only scratch buffers for the full (SCROLL1+SCROLL2+SCROLL3+sprites+
 * compositor) render path -- see cps1_core_run_frame(). Not per-engine:
 * reused sequentially, single-threaded, cleared fresh every call. */
static uint16_t s_bottom_fb[CPS1_FB_WIDTH * CPS1_FB_HEIGHT];
static uint16_t s_middle_fb[CPS1_FB_WIDTH * CPS1_FB_HEIGHT];
static uint16_t s_top_fb[CPS1_FB_WIDTH * CPS1_FB_HEIGHT];

#define CPS1_SOUND_SAMPLES_PER_FRAME (CPS1_SOUND_SAMPLE_RATE / 60u) /* ~368 @ 60fps */

void cps1_core_reset(cps1_engine_kind_t engine)
{
    cps1_ppu_init_synthetic();
    cps1_bg_init_synthetic();
    cps1_sound_init_synthetic();
    cps1_gfxram_init_synthetic();

    cps1_engine_state_t *e = &s_engine[engine];
    e->frame = 0;
    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++)
        e->fb[i] = 0;
    cps1_cpu68k_reset(&e->cpu, s_cpu_test_program, sizeof(s_cpu_test_program));
    cps1_cpu68k_attach_bus(&e->cpu, &s_bus);

    /* Nothing has been latched yet -- matches real hardware's first frame
     * showing no sprites until the first vblank latch happens. */
    s_buffered_obj.count = 0;
}

/* docs/CPS1_MAME_ALIGNMENT.md section 5, cps1_objram_latch: copies the
 * CURRENT (CPU-writable) OAM into the buffer the renderer actually reads,
 * so this frame's CPU writes only become visible starting NEXT frame. */
static void cps1_core_latch_obj(void)
{
    s_buffered_obj = s_synthetic_oam;
}

static void cps1_core_step_cpu(cps1_engine_state_t *e, cps1_engine_kind_t engine)
{
    if (engine == CPS1_ENGINE_RECOMPILER) {
        if (!e->cpu.halted)
            cps1_rc_translated(&e->cpu);
    } else {
        cps1_cpu68k_run(&e->cpu, CPS1_CPU_MAX_STEPS_PER_FRAME);
    }
}

static void cps1_core_mix_sound_frame(void)
{
    int16_t scratch[CPS1_SOUND_SAMPLES_PER_FRAME];
    cps1_sound_hle_mix(&s_sound, scratch, CPS1_SOUND_SAMPLES_PER_FRAME);
}

/* Full pipeline: every layer rendered into its own buffer + the host
 * compositor (cheat 8's software stand-in for LTDC). This is what makes
 * the layer separation visually/checksum-verifiable off real hardware
 * (main_cps1.c's --dump-ppm, the diff harness) -- it is NOT what should be
 * profiled for device fps; see cps1_core_run_frame_device_cost(). */
void cps1_core_run_frame(cps1_engine_kind_t engine)
{
    cps1_engine_state_t *e = &s_engine[engine];
    e->frame++;

    cps1_core_step_cpu(e, engine);

    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++) {
        s_bottom_fb[i] = 0;
        s_middle_fb[i] = 0;
        s_top_fb[i] = 0;
    }
    cps1_bg_render_layer(&s_bg.layers[CPS1_BG_SCROLL1], CPS1_BG_SCROLL1, &s_synthetic_rom,
                          &s_tile_cache, &s_synthetic_palette, s_bottom_fb);
    cps1_bg_render_layer(&s_bg.layers[CPS1_BG_SCROLL2], CPS1_BG_SCROLL2, &s_synthetic_rom,
                          &s_tile_cache, &s_synthetic_palette, s_middle_fb);
    cps1_bg_render_layer(&s_bg.layers[CPS1_BG_SCROLL3], CPS1_BG_SCROLL3, &s_synthetic_rom,
                          &s_tile_cache, &s_synthetic_palette, s_top_fb);
    cps1_ppu_render(&s_buffered_obj, &s_synthetic_rom, &s_tile_cache, &s_synthetic_palette, s_top_fb);
    cps1_compositor_blend(s_bottom_fb, s_middle_fb, s_top_fb, e->fb);

    cps1_core_mix_sound_frame();
    cps1_core_latch_obj();
}

/*
 * Device-realistic pipeline (docs/CPS1_SENIOR_TRICKS_ANALYSIS.md cheat 8):
 * CPU + SCROLL3 render + sprites, straight into the engine's own buffer --
 * SCROLL1/SCROLL2 render and the bottom+middle blend are skipped entirely,
 * because on real hardware those become LTDC hardware layers/scanout
 * blending and cost the CPU nothing. THIS is the function to profile
 * against the 60fps budget, not cps1_core_run_frame() (which additionally
 * pays for the host-only compositor stand-in so the layers are checkable
 * without real LTDC silicon). */
void cps1_core_run_frame_device_cost(cps1_engine_kind_t engine)
{
    cps1_engine_state_t *e = &s_engine[engine];
    e->frame++;

    cps1_core_step_cpu(e, engine);

    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++)
        e->fb[i] = 0;
    cps1_bg_render_layer(&s_bg.layers[CPS1_BG_SCROLL3], CPS1_BG_SCROLL3, &s_synthetic_rom,
                          &s_tile_cache, &s_synthetic_palette, e->fb);
    cps1_ppu_render(&s_buffered_obj, &s_synthetic_rom, &s_tile_cache, &s_synthetic_palette, e->fb);

    cps1_core_mix_sound_frame();
    cps1_core_latch_obj();
}

const uint16_t *cps1_core_get_framebuffer(cps1_engine_kind_t engine)
{
    return s_engine[engine].fb;
}

uint32_t cps1_core_checksum(cps1_engine_kind_t engine)
{
    const uint16_t *fb = s_engine[engine].fb;
    uint32_t h = 2166136261u;
    for (int i = 0; i < CPS1_FB_WIDTH * CPS1_FB_HEIGHT; i++) {
        h ^= fb[i];
        h *= 16777619u;
    }
    return h;
}

uint32_t cps1_core_cpu_state_hash(cps1_engine_kind_t engine)
{
    return cps1_cpu68k_state_hash(&s_engine[engine].cpu);
}

uint32_t cps1_core_cpu_illegal_count(cps1_engine_kind_t engine)
{
    return s_engine[engine].cpu.illegal_count;
}

uint16_t cps1_core_wram_peek16(uint32_t offset)
{
    if (offset + 1 >= CPS1_WRAM_SIZE)
        return 0;
    return (uint16_t)((s_wram[offset] << 8) | s_wram[offset + 1]);
}

int cps1_core_oam_peek(uint32_t index, int16_t *out_x, int16_t *out_y,
                        uint16_t *out_tile, uint8_t *out_attr)
{
    if (index >= s_synthetic_oam.count)
        return 0;
    const cps1_oam_entry_t *s = &s_synthetic_oam.sprites[index];
    if (out_x)    *out_x = s->x;
    if (out_y)    *out_y = s->y;
    if (out_tile) *out_tile = s->tile_index;
    if (out_attr) *out_attr = s->attr;
    return 1;
}

int cps1_core_buffered_oam_peek(uint32_t index, int16_t *out_x, int16_t *out_y,
                                 uint16_t *out_tile, uint8_t *out_attr)
{
    if (index >= s_buffered_obj.count)
        return 0;
    const cps1_oam_entry_t *s = &s_buffered_obj.sprites[index];
    if (out_x)    *out_x = s->x;
    if (out_y)    *out_y = s->y;
    if (out_tile) *out_tile = s->tile_index;
    if (out_attr) *out_attr = s->attr;
    return 1;
}

uint16_t cps1_core_palette_peek(unsigned bank, unsigned color)
{
    if (bank >= CPS1_PALETTE_BANKS || color >= CPS1_PALETTE_COLORS)
        return 0;
    return s_synthetic_palette.colors[bank][color];
}

/*
 * Hand-assembled: sets up A0/A1/A2 to WRAM/OBJ-RAM(sprite 0's Y
 * word)/palette-RAM(bank 1, color 2), writes a distinct MOVEQ-range value
 * through each, and reads WRAM back into D1 to prove the round trip.
 *   MOVEA.L #CPS1_WRAM_BASE,A0 ; MOVEQ #7,D0  ; MOVE.W D0,(A0) ; MOVE.W (A0),D1
 *   MOVEA.L #<default OBJ addr>,A1  ; MOVEQ #99,D2 ; MOVE.W D2,(A1)
 *   MOVEA.L #<default PALETTE addr + 36>,A2 ; MOVEQ #21,D3 ; MOVE.W D3,(A2)
 *   RTS
 * (palette bank 1 color 2 -> word index 1*16+2=18 -> byte offset 36; Phase 9
 * addresses: OBJ default offset 0 -> 0x900000, PALETTE default offset
 * 0x14000 -> 0x914000+36=0x914024 -- see CPS1_DEFAULT_*_OFFSET above.)
 */
static const uint8_t s_vdp_bus_test_program[] = {
    0x20, 0x7C, 0x00, 0xFF, 0x00, 0x00, /* MOVEA.L #0xFF0000,A0 */
    0x70, 0x07,                         /* MOVEQ   #7,D0        */
    0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
    0x32, 0x10,                         /* MOVE.W  (A0),D1      */
    0x22, 0x7C, 0x00, 0x90, 0x00, 0x00, /* MOVEA.L #0x900000,A1 */
    0x74, 0x63,                         /* MOVEQ   #99,D2       */
    0x32, 0x82,                         /* MOVE.W  D2,(A1)      */
    0x24, 0x7C, 0x00, 0x91, 0x40, 0x24, /* MOVEA.L #0x914024,A2 */
    0x76, 0x15,                         /* MOVEQ   #21,D3       */
    0x34, 0x83,                         /* MOVE.W  D3,(A2)      */
    0x4E, 0x75,                         /* RTS                  */
};

int cps1_core_selftest_vdp_bus(void)
{
    cps1_ppu_init_synthetic();
    cps1_gfxram_init_synthetic(); /* OBJ/PALETTE resolve via CPS-A registers now (Phase 9) */

    cps1_cpu68k_t cpu;
    cps1_cpu68k_reset(&cpu, s_vdp_bus_test_program, sizeof(s_vdp_bus_test_program));
    cps1_cpu68k_attach_bus(&cpu, &s_bus);
    cps1_cpu68k_run(&cpu, 64);

    if (!cpu.halted || cpu.illegal_count != 0)
        return 0;
    if (cpu.d[1] != 7)
        return 0; /* WRAM round-trip, via register */
    if (cps1_core_wram_peek16(0) != 7)
        return 0; /* WRAM round-trip, via memory directly */
    if (s_synthetic_oam.sprites[0].y != 99)
        return 0; /* OBJ RAM write actually moved sprite 0 */
    /* The bus stores cps1_palette_build(raw), not the raw word directly
     * (see cps1_bus_write16's palette branch) -- compute the same
     * conversion here rather than a raw literal, so this test tracks the
     * real write path instead of assuming pass-through. cps1_ppu.c's own
     * cps1_palette_build is hand-verified separately against MAME's
     * formula (docs/CPS1_MAME_ALIGNMENT.md section 2). */
    if (s_synthetic_palette.colors[1][2] != cps1_palette_build(21))
        return 0; /* palette RAM write actually recolored bank 1 color 2 */
    return 1;
}

int cps1_core_sound_tone_active(unsigned channel)
{
    if (channel >= CPS1_SOUND_TONE_CHANNELS)
        return 0;
    return s_sound.tone[channel].enabled;
}

void cps1_core_sound_mix(int16_t *out, uint32_t count)
{
    cps1_sound_hle_mix(&s_sound, out, count);
}

/*
 * Hand-assembled: MOVEA.L #CPS1_SOUND_CMD_BASE,A0 ; MOVEQ #4,D0 (command
 * 0x04 = note 1, tone channel 0, see cps1_sound_hle_trigger) ;
 * MOVE.W D0,(A0) ; RTS. Phase 9 moved CPS1_SOUND_CMD_BASE to 0x800180
 * (the real non-QSound soundlatch address) since 0x920000 now falls
 * inside the shared gfxram pool.
 */
static const uint8_t s_sound_bus_test_program[] = {
    0x20, 0x7C, 0x00, 0x80, 0x01, 0x80, /* MOVEA.L #0x800180,A0 */
    0x70, 0x04,                         /* MOVEQ   #4,D0        */
    0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
    0x4E, 0x75,                         /* RTS                  */
};

int cps1_core_selftest_sound_bus(void)
{
    cps1_sound_init_synthetic();

    cps1_cpu68k_t cpu;
    cps1_cpu68k_reset(&cpu, s_sound_bus_test_program, sizeof(s_sound_bus_test_program));
    cps1_cpu68k_attach_bus(&cpu, &s_bus);
    cps1_cpu68k_run(&cpu, 64);

    if (!cpu.halted || cpu.illegal_count != 0)
        return 0;
    if (!s_sound.tone[0].enabled)
        return 0; /* the 68000 write reached cps1_sound_hle_trigger */
    if (s_sound.tone[0].phase_step == 0)
        return 0; /* trigger actually set up a real, non-zero frequency */
    return 1;
}

int cps1_core_bg_cell_peek(unsigned layer, uint32_t index, uint16_t *out_tile,
                            uint8_t *out_palette, uint8_t *out_enabled)
{
    if (layer >= CPS1_BG_LAYER_COUNT || index >= (uint32_t)CPS1_BG_MAP_W * CPS1_BG_MAP_H)
        return 0;
    const cps1_bg_cell_t *cell = &s_bg.layers[layer].cells[index];
    if (out_tile)    *out_tile = cell->tile_index;
    if (out_palette) *out_palette = cell->palette;
    if (out_enabled) *out_enabled = cell->enabled;
    return 1;
}

/*
 * Hand-assembled: sets SCROLL1 (layer 0) cell 0's tile_index to 7 and its
 * palette/enabled word to 0x0105 (palette=5, enabled=1 -- needs the 16-bit
 * MOVE.W #imm,Dn immediate since 0x0105 is out of MOVEQ's -128..127 range).
 * Phase 9: SCROLL1's default gfxram offset is 0x4000 -> absolute 0x904000
 * (CPS1_DEFAULT_SCROLL1_OFFSET above), not the old fixed 0x930000.
 *   MOVEA.L #0x904000,A0 ; MOVEQ #7,D0       ; MOVE.W D0,(A0)
 *   MOVEA.L #0x904002,A1 ; MOVE.W #0x0105,D1 ; MOVE.W D1,(A1)
 *   RTS
 */
static const uint8_t s_bg_bus_test_program[] = {
    0x20, 0x7C, 0x00, 0x90, 0x40, 0x00, /* MOVEA.L #0x904000,A0 */
    0x70, 0x07,                         /* MOVEQ   #7,D0        */
    0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
    0x22, 0x7C, 0x00, 0x90, 0x40, 0x02, /* MOVEA.L #0x904002,A1 */
    0x32, 0x3C, 0x01, 0x05,             /* MOVE.W  #0x0105,D1   */
    0x32, 0x81,                         /* MOVE.W  D1,(A1)      */
    0x4E, 0x75,                         /* RTS                  */
};

int cps1_core_selftest_bg_bus(void)
{
    cps1_bg_init_synthetic();
    cps1_gfxram_init_synthetic(); /* SCROLL1/2/3 resolve via CPS-A registers now (Phase 9) */

    cps1_cpu68k_t cpu;
    cps1_cpu68k_reset(&cpu, s_bg_bus_test_program, sizeof(s_bg_bus_test_program));
    cps1_cpu68k_attach_bus(&cpu, &s_bus);
    cps1_cpu68k_run(&cpu, 64);

    if (!cpu.halted || cpu.illegal_count != 0)
        return 0;
    uint16_t tile = 0;
    uint8_t palette = 0, enabled = 0;
    if (!cps1_core_bg_cell_peek(CPS1_BG_SCROLL1, 0, &tile, &palette, &enabled))
        return 0;
    if (tile != 7 || palette != 5 || enabled != 1)
        return 0;
    return 1;
}

/*
 * Hand-assembled template: MOVEA.L #0x900000,A0 (default OBJ base + sprite
 * 0's Y word) ; MOVE.W #<Y>,D0 (patched per call) ; MOVE.W D0,(A0) ; RTS.
 * A local (non-static) copy so the immediate at bytes [8:9] can be patched
 * with a different Y value each call.
 */
static int cps1_run_obj_write_y(int16_t y_value)
{
    uint8_t prog[] = {
        0x20, 0x7C, 0x00, 0x90, 0x00, 0x00, /* MOVEA.L #0x900000,A0 */
        0x30, 0x3C, 0x00, 0x00,             /* MOVE.W  #<Y>,D0      */
        0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
        0x4E, 0x75,                         /* RTS                  */
    };
    prog[8] = (uint8_t)((uint16_t)y_value >> 8);
    prog[9] = (uint8_t)((uint16_t)y_value & 0xFFu);

    cps1_cpu68k_t writer;
    cps1_cpu68k_reset(&writer, prog, sizeof(prog));
    cps1_cpu68k_attach_bus(&writer, &s_bus);
    cps1_cpu68k_run(&writer, 32);
    return writer.halted && writer.illegal_count == 0;
}

int cps1_core_selftest_obj_delay(void)
{
    /* cps1_core_reset() also zeroes s_buffered_obj.count -- must run before
     * any of this test's own bus writes, and this test must run before any
     * OTHER test relocates OBJ_BASE away from its default (0x900000). */
    cps1_core_reset(CPS1_ENGINE_INTERPRETER);

    if (!cps1_run_obj_write_y(111))
        return 0;
    if (s_synthetic_oam.sprites[0].y != 111)
        return 0; /* live table: immediate */

    int16_t by = -1;
    if (cps1_core_buffered_oam_peek(0, NULL, &by, NULL, NULL))
        return 0; /* nothing latched yet (count==0 right after reset) */

    cps1_core_run_frame(CPS1_ENGINE_INTERPRETER); /* runs+renders+LATCHES */

    by = -1;
    if (!cps1_core_buffered_oam_peek(0, NULL, &by, NULL, NULL) || by != 111)
        return 0; /* frame 1's latch made it visible */

    if (!cps1_run_obj_write_y(222))
        return 0;
    if (s_synthetic_oam.sprites[0].y != 222)
        return 0; /* live table already shows the new write */

    by = -1;
    if (!cps1_core_buffered_oam_peek(0, NULL, &by, NULL, NULL) || by != 111)
        return 0; /* buffered/rendered table must still show the OLD value */

    cps1_core_run_frame(CPS1_ENGINE_INTERPRETER); /* second latch */

    by = -1;
    if (!cps1_core_buffered_oam_peek(0, NULL, &by, NULL, NULL) || by != 222)
        return 0; /* now caught up */

    return 1;
}

/*
 * Hand-assembled: moves OBJ_BASE (CPS-A register at 0x800100) to gfxram
 * offset 0x18000 (reg value 0x180 -- 0x18000/256), writes sprite 0's Y
 * field at the NEWLY-resolved absolute address (0x900000+0x18000=
 * 0x918000), then writes a different value at the OLD default OBJ address
 * (0x900000) to prove that address no longer aliases sprite 0.
 *   MOVEA.L #0x800100,A0 ; MOVE.W #0x0180,D0 ; MOVE.W D0,(A0)
 *   MOVEA.L #0x918000,A1 ; MOVEQ #55,D1      ; MOVE.W D1,(A1)
 *   MOVEA.L #0x900000,A2 ; MOVEQ #99,D2      ; MOVE.W D2,(A2)
 *   RTS
 */
static const uint8_t s_obj_relocation_test_program[] = {
    0x20, 0x7C, 0x00, 0x80, 0x01, 0x00, /* MOVEA.L #0x800100,A0 */
    0x30, 0x3C, 0x01, 0x80,             /* MOVE.W  #0x0180,D0   */
    0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
    0x22, 0x7C, 0x00, 0x91, 0x80, 0x00, /* MOVEA.L #0x918000,A1 */
    0x72, 0x37,                         /* MOVEQ   #55,D1       */
    0x32, 0x81,                         /* MOVE.W  D1,(A1)      */
    0x24, 0x7C, 0x00, 0x90, 0x00, 0x00, /* MOVEA.L #0x900000,A2 */
    0x74, 0x63,                         /* MOVEQ   #99,D2       */
    0x34, 0x82,                         /* MOVE.W  D2,(A2)      */
    0x4E, 0x75,                         /* RTS                  */
};

int cps1_core_selftest_obj_relocation(void)
{
    cps1_ppu_init_synthetic();
    cps1_gfxram_init_synthetic();

    cps1_cpu68k_t cpu;
    cps1_cpu68k_reset(&cpu, s_obj_relocation_test_program, sizeof(s_obj_relocation_test_program));
    cps1_cpu68k_attach_bus(&cpu, &s_bus);
    cps1_cpu68k_run(&cpu, 64);

    if (!cpu.halted || cpu.illegal_count != 0)
        return 0;
    if (s_cps_a_regs[CPS1_REG_OBJ_BASE] != 0x0180)
        return 0; /* the register write itself landed */
    if (s_synthetic_oam.sprites[0].y != 55)
        return 0; /* write at the NEW resolved address landed on sprite 0 */
    return 1; /* the stray write to the OLD address (0x900000, now plain
                 gfxram) must NOT have overwritten sprite 0.y back to 99 --
                 already implied by the check above, since both writes ran
                 and only one value can be there. */
}

/*
 * Hand-assembled: moves PALETTE_BASE (CPS-A register at 0x80010A) to
 * gfxram offset 0x1C000 (reg value 0x1C0), writes a raw palette word at
 * the NEWLY-resolved absolute address for bank 0 color 1
 * (0x900000+0x1C000+2=0x91C002), then writes a different raw word at the
 * OLD default palette address for bank 0 color 1 (0x900000+0x14000+2=
 * 0x914002) to prove that address no longer aliases that color.
 *   MOVEA.L #0x80010A,A0 ; MOVE.W #0x01C0,D0 ; MOVE.W D0,(A0)
 *   MOVEA.L #0x91C002,A1 ; MOVE.W #0x0F0F,D1 ; MOVE.W D1,(A1)
 *   MOVEA.L #0x914002,A2 ; MOVEQ #7,D2       ; MOVE.W D2,(A2)
 *   RTS
 */
static const uint8_t s_palette_relocation_test_program[] = {
    0x20, 0x7C, 0x00, 0x80, 0x01, 0x0A, /* MOVEA.L #0x80010A,A0 */
    0x30, 0x3C, 0x01, 0xC0,             /* MOVE.W  #0x01C0,D0   */
    0x30, 0x80,                         /* MOVE.W  D0,(A0)      */
    0x22, 0x7C, 0x00, 0x91, 0xC0, 0x02, /* MOVEA.L #0x91C002,A1 */
    0x32, 0x3C, 0x0F, 0x0F,             /* MOVE.W  #0x0F0F,D1   */
    0x32, 0x81,                         /* MOVE.W  D1,(A1)      */
    0x24, 0x7C, 0x00, 0x91, 0x40, 0x02, /* MOVEA.L #0x914002,A2 */
    0x74, 0x07,                         /* MOVEQ   #7,D2        */
    0x34, 0x82,                         /* MOVE.W  D2,(A2)      */
    0x4E, 0x75,                         /* RTS                  */
};

int cps1_core_selftest_palette_relocation(void)
{
    cps1_ppu_init_synthetic();
    cps1_gfxram_init_synthetic();

    cps1_cpu68k_t cpu;
    cps1_cpu68k_reset(&cpu, s_palette_relocation_test_program,
                       sizeof(s_palette_relocation_test_program));
    cps1_cpu68k_attach_bus(&cpu, &s_bus);
    cps1_cpu68k_run(&cpu, 64);

    if (!cpu.halted || cpu.illegal_count != 0)
        return 0;
    if (s_cps_a_regs[CPS1_REG_PALETTE_BASE] != 0x01C0)
        return 0; /* the register write itself landed */
    if (s_synthetic_palette.colors[0][1] != cps1_palette_build(0x0F0F))
        return 0; /* write at the NEW resolved address landed, converted */
    return 1;
}
